create or replace 
FUNCTION FN_GET_NUMBERCODE(V_IDA2A2 IN VARCHAR2)
RETURN  VARCHAR2
IS
    V_RETURN VARCHAR2(200);
   
BEGIN
    SELECT CODE INTO V_RETURN
      FROM NUMBERCODE
     WHERE IDA2A2 = V_IDA2A2;
     
     RETURN V_RETURN;
END;