var res_helpitem = new Array();
var res_helpitem_MainTitle_Sub = new Array();
var res_helpitem_MainDescription = new Array();
var res_helpitem_SubDescription_1 = new Array();

res_helpitem[0] = new Array();
res_helpitem[1] = new Array();
res_helpitem[2] = new Array();
res_helpitem[3] = new Array();
res_helpitem[4] = new Array();

res_helpitem_MainDescription[0] = new Array();
res_helpitem_MainDescription[1] = new Array();
res_helpitem_MainDescription[2] = new Array();
res_helpitem_MainDescription[3] = new Array();
res_helpitem_MainDescription[4] = new Array();


res_helpitem[0][0] = "글꼴";
res_helpitem[0][1] = "글크기";
res_helpitem[0][2] = "굵게";
res_helpitem[0][3] = "기울림꼴";
res_helpitem[0][4] = "밑줄";
res_helpitem[0][5] = "전경색";
res_helpitem[0][6] = "배경색";
res_helpitem[0][7] = "왼쪽 맞춤";
res_helpitem[0][8] = "가운데 맞춤";
res_helpitem[0][9] = "오른쪽 맞춤";
res_helpitem[0][10] = "번호매기기";
res_helpitem[0][11] = "글머리기호";
res_helpitem[0][12] = "글 간격";
res_helpitem[0][13] = "줄 간격";
res_helpitem[0][14] = "취소선";
res_helpitem[0][15] = "아래첨자";
res_helpitem[0][16] = "위첨자";
res_helpitem[0][17] = "내어쓰기";
res_helpitem[0][18] = "들여쓰기";

res_helpitem[1][0] = "표 생성";
res_helpitem[1][1] = "행 추가";
res_helpitem[1][2] = "행 삭제";
res_helpitem[1][3] = "열 추가";
res_helpitem[1][4] = "열 삭제";
res_helpitem[1][5] = "셀 병합";
res_helpitem[1][6] = "행 분할";
res_helpitem[1][7] = "열 분할";
res_helpitem[1][8] = "표 템플릿";
res_helpitem[1][9] = "표 속성 개요";
res_helpitem[1][10] = "표 속성 세부(1)";
res_helpitem[1][11] = "표 속성 세부(2)";
res_helpitem[1][12] = "표 속성 세부(3)";
res_helpitem[1][13] = "셀 속성 개요";
res_helpitem[1][14] = "셀 속성 세부(1)";
res_helpitem[1][15] = "셀 속성 세부(2)";

res_helpitem[2][0] = "잘라내기";
res_helpitem[2][1] = "복사";
res_helpitem[2][2] = "붙여넣기";
res_helpitem[2][3] = "삭제";
res_helpitem[2][4] = "전체 선택";

res_helpitem[3][0] = "링크 연결";
res_helpitem[3][1] = "링크 제거";
res_helpitem[3][2] = "이미지 삽입";
res_helpitem[3][3] = "이미지 속성";
res_helpitem[3][4] = "플래시 삽입";
res_helpitem[3][5] = "플래시 속성";
res_helpitem[3][6] = "동영상 삽입";
res_helpitem[3][7] = "동영상 속성";
res_helpitem[3][8] = "특수문자";
res_helpitem[3][9] = "문서 배경색";
res_helpitem[3][10] = "문서 배경이미지";
res_helpitem[3][11] = "문서 템플릿";

res_helpitem[4][0] = "제품 도움말";
res_helpitem[4][1] = "제품 정보";

res_helpitem_MainTitle_Sub[0] = "";
res_helpitem_MainTitle_Sub[1] = "";
res_helpitem_MainTitle_Sub[2] = "";
res_helpitem_MainTitle_Sub[3] = "";
res_helpitem_MainTitle_Sub[4] = "";
res_helpitem_MainTitle_Sub[5] = "";
res_helpitem_MainTitle_Sub[6] = "";
res_helpitem_MainTitle_Sub[7] = "";
res_helpitem_MainTitle_Sub[8] = "";
res_helpitem_MainTitle_Sub[9] = "";
res_helpitem_MainTitle_Sub[10] = " - 테이블 테두리 적용 설정";
res_helpitem_MainTitle_Sub[11] = " - 테이블 테두리 설정";
res_helpitem_MainTitle_Sub[12] = " - 테이블 셀 간격/여백 설정";
res_helpitem_MainTitle_Sub[13] = " - 테두리/색상";
res_helpitem_MainTitle_Sub[14] = " - 테두리 설정";
res_helpitem_MainTitle_Sub[15] = " - 크기/정렬";

res_helpitem_MainDescription[0][0] = "변경하고자 하는 영역을 선택하고 글꼴 콤보박스에서 원하시는 글꼴을 선택하시면 해당 글꼴로 변경됩니다.";
res_helpitem_MainDescription[0][1] = "변경하고자 하는 영역을 선택하고 글크기 콤보박스에서 원하시는 크기를 선택하시면 해당 크기로 변경됩니다.";
res_helpitem_MainDescription[0][2] = "변경하고자 하는 영역을 선택하고 굵게 버튼을 선택하시면 글이 굵게 변경됩니다.<br />이미 글이 굵게 되어있는 경우 굵게 버튼을 다시 선택하시면 원래 상태로 변경됩니다.";
res_helpitem_MainDescription[0][3] = "변경하고자 하는 영역을 선택하고 기울림꼴 버튼을 선택하시면 글이 기울림꼴로 변경됩니다.<br />이미 글이 기울림꼴로 되어있는 경우 기울림꼴 버튼을 다시 선택하시면 원래 상태로 변경됩니다.";
res_helpitem_MainDescription[0][4] = "변경하고자 하는 영역을 선택하고 밑줄 버튼을 선택하시면 글이 밑줄이 적용되어 변경됩니다.<br />이미 글이 밑줄이 적용되어 있는 경우 밑줄 버튼을 다시 선택하시면 원래 상태로 변경됩니다.";
res_helpitem_MainDescription[0][5] = "변경하고자 하는 영역을 선택하고 전경색 드랍다운 버튼을 선택하시어 원하시는 색상을 선택하면<br />글의 전경색이 선택된 색상으로 적용됩니다.";
res_helpitem_MainDescription[0][6] = "변경하고자 하는 영역을 선택하고 배경색 드랍다운 버튼을 선택하시어 원하시는 색상을 선택하면<br />글의 배경색이 선택된 색상으로 적용됩니다.";
res_helpitem_MainDescription[0][7] = "맞춤을 적용하고자 하는 영역을 선택하고 왼쪽 맞춤 버튼을 선택하시면 글의 왼쪽 맞춤이 적용되어 변경됩니다.";
res_helpitem_MainDescription[0][8] = "맞춤을 적용하고자 하는 영역을 선택하고 가운데 맞춤 버튼을 선택하시면 글의 가운데 맞춤이 적용되어 변경됩니다.";
res_helpitem_MainDescription[0][9] = "맞춤을 적용하고자 하는 영역을 선택하고 오른쪽 맞춤 버튼을 선택하시면 글의 오른쪽 맞춤이 적용되어 변경됩니다.";
res_helpitem_MainDescription[0][10] = "글의 앞 부분에 자동으로 글 번호가 생성되도록 하고자 하는 경우 해당 영역을 선택하고 번호매기기 버튼을<br />선택하시면 글의 앞부분에 자동으로 글 번호가 적용됩니다.<br />이미 번호매기기가 적용되어 있는 경우 번호매기기 버튼을 다시 선택하시면 원래 상태로 변경됩니다.";
res_helpitem_MainDescription[0][11] = "글의 앞 부분에 자동으로 글 머리기호가 생성되도록 하고자 하는 경우 해당 영역을 선택하고 글머리기호 버튼을<br />선택하시면 글의 앞부분에 자동으로 글머리기호가 적용됩니다.<br />이미 글머리기호가 적용되어 있는 경우 글머리기호 버튼을 다시 선택하시면 원래 상태로 변경됩니다.";
res_helpitem_MainDescription[0][12] = "변경하고자 하는 영역을 선택하고 글간격 드랍다운 버튼을 선택하시어 원하시는 글간격을 선택하면<br />글의 간격이 선택된 간격으로 적용됩니다.";
res_helpitem_MainDescription[0][13] = "변경하고자 하는 영역을 선택하고 줄간격 드랍다운 버튼을 선택하시어 원하시는 줄간격을 선택하면<br />줄의 간격이 선택된 간격으로 적용됩니다.";
res_helpitem_MainDescription[0][14] = "변경하고자 하는 영역을 선택하고 취소선 버튼을 선택하시면 글의 중간부분에 밑줄이 생성되는 취소선이 적용됩니다.<br />이미 글이 취소선이 적용되어 있는 경우 취소선 버튼을 다시 선택하시면 원래 상태로 변경됩니다.";
res_helpitem_MainDescription[0][15] = "변경하고자 하는 영역을 선택하고 아래첨자 버튼을 선택하시면 글의 하단부분에 첨자가 생성되는 아래첨자가<br />적용됩니다. 이미 글이 아래첨자가 적용되어 있는 경우 아래첨자 버튼을 다시 선택하시면 원래 상태로 변경됩니다.";
res_helpitem_MainDescription[0][16] = "변경하고자 하는 영역을 선택하고 위첨자 버튼을 선택하시면 글의 상단부분에 첨자가 생성되는 위첨자가 적용됩니다.<br />이미 글이 위첨자가 적용되어 있는 경우 위첨자 버튼을 다시 선택하시면 원래 상태로 변경됩니다.";
res_helpitem_MainDescription[0][17] = "변경하고자 하는 영역을 선택하고 내어쓰기 버튼을 선택하시면 글 라인의 앞 부분에 여백없이 글이 적용됩니다.";
res_helpitem_MainDescription[0][18] = "변경하고자 하는 영역을 선택하고 들여쓰기 버튼을 선택하시면 글 라인의 앞 부분에 여백이 발생하여 글이 적용됩니다.";

res_helpitem_MainDescription[1][0] = "표생성 드랍다운 버튼을 선택하시면 테이블 행X열을 선택하는 창이 나타나며 마우스로 원하는 행열의 위치로<br />이동 후 선택하면 편집창에 테이블이 생성됩니다.";
res_helpitem_MainDescription[1][1] = "표의 단일 셀 또는 단일 행, 다중 행 전체를 선택하면 행 추가 버튼이 활성화되며, 행 추가 버튼을 선택하면<br />이전에 선택된 영역 위 부분에 선택된 행의 갯수만큼 행이 추가됩니다.";
res_helpitem_MainDescription[1][2] = "표의 단일 행, 다중 행 전체를 선택하면 행 삭제 버튼이 활성화되며, 행 삭제 버튼을 선택하면 선택된 영역이<br />삭제됩니다.";
res_helpitem_MainDescription[1][3] = "표의 단일 셀 또는 단일 열, 다중 열 전체를 선택하면 열 추가 버튼이 활성화되며, 열 추가 버튼을 선택하면<br />이전에 선택된 영역 왼쪽 부분에 선택된 열의 갯수만큼 열이 추가됩니다.";
res_helpitem_MainDescription[1][4] = "표의 단일 열, 다중 열 전체를 선택하면 열 삭제 버튼이 활성화되며, 열 삭제 버튼을 선택하면 선택된 영역이<br />삭제됩니다.";
res_helpitem_MainDescription[1][5] = "표의 다중 셀을 선택하면 셀 병합 버튼이 활성화되며, 셀 병합 버튼을 선택하면 이전에 선택된 영역 부분이 병합됩니다.";
res_helpitem_MainDescription[1][6] = "표의 다중 셀을 선택한 후 행 분할이 가능한 상태이면 행 분할 버튼이 활성화되며, 행 분할 버튼을 선택하면<br />이전에 선택된 영역 부분의 행이 분할됩니다.";
res_helpitem_MainDescription[1][7] = "표의 다중 셀을 선택한 후 열 분할이 가능한 상태이면 열 분할 버튼이 활성화되며, 열 분할 버튼을 선택하면<br />이전에 선택된 영역 부분의 열이 분할됩니다.";
res_helpitem_MainDescription[1][8] = "생성하고자 하는 표 템플릿을 선택하면 해당 스타일의 표가 생성됩니다.";
res_helpitem_MainDescription[1][9] = "표안의 셀 일부를 선택하고 메뉴 또는 팝업메뉴에서 테이블 속성을 선택하면 세부 속성을 설정할 수 있는 팝업창이<br />생성되며, 팝업창에서 각각의 속성에 따른 세부 설정을 지정 및 미리보기를 통하여 확인 후 적용합니다.";
res_helpitem_MainDescription[1][10] = "테두리 합치기 부분과 셀 동시 적용 여부를 설정합니다.";
res_helpitem_MainDescription[1][11] = "테이블 테두리의 형태, 크기, 색상 및 Left, Top, Right, Bottom 개별 적용 여부를 설정합니다.";
res_helpitem_MainDescription[1][12] = "테이블 셀 간격/여백을 설정합니다.(셀 간격 - cellspacing, 셀 여백 - cellpadding)<br />외곽선 합치기 여부와 테이블 테두리를 제거여부 등에 따라 다양한 형태를 표시합니다.";
res_helpitem_MainDescription[1][13] = "표안의 셀 일부를 선택하고 메뉴 또는 팝업메뉴에서 셀 속성을 선택하면 세부 속성을 설정할 수 있는 팝업창이<br />생성되며, 팝업창에서 각각의 속성에 따른 세부 설정을 지정 및 미리보기를 통하여 확인 후 적용합니다.";
res_helpitem_MainDescription[1][14] = "선택된 셀에 대하여 테두리의 형태, 크기, 색상, 표시여부를 각각 설정합니다.";
res_helpitem_MainDescription[1][15] = "표안의 셀 일부를 선택하고 메뉴 또는 팝업메뉴에서 셀 속성을 선택하면 세부 속성을 설정할 수 있는 팝업창이<br />생성되며, 팝업창 우측 상단의 크기/정렬 버튼을 선택하면 크기와 레이아웃을 설정할 수 있는 세부 설정창이<br />표시됩니다.";

res_helpitem_MainDescription[2][0] = "잘라내기를 하고자 하는 영역을 선택하시고 메뉴의 편집->잘라내기, 키보드(Ctrl+X) 또는 팝업메뉴에서 잘라내기를<br />선택하면 이전에 선택된 영역이 잘라내기가 실행됩니다.";
res_helpitem_MainDescription[2][1] = "복사를 하고자 하는 영역을 선택하시고 메뉴의 편집->복사, 키보드(Ctrl+C) 또는 팝업메뉴에서 복사를 선택하면<br />이전에 선택된 영역이 복사가 실행됩니다.";
res_helpitem_MainDescription[2][2] = "붙여넣기를 하고자 하는 영역을 선택하시고 메뉴의 편집->붙여넣기, 키보드(Ctrl+V) 또는 팝업메뉴에서 붙여넣기를<br />선택하면 이전에 선택된 영역에 붙여넣기가 실행됩니다.";
res_helpitem_MainDescription[2][3] = "삭제를 하고자 하는 영역을 선택하시고 메뉴의 편집->삭제 또는 키보드(Delete)를 선택하면<br />이전에 선택된 영역에 삭제가 실행됩니다.";
res_helpitem_MainDescription[2][4] = "전체 영역을 선택하고자 할때 메뉴의 편집->전체 선택 또는 키보드(Ctrl+A)를 선택하면<br />전체 영역이 선택됩니다.";

res_helpitem_MainDescription[3][0] = "하이퍼링크를 하고자 하는 영역을 선택하시고 하이퍼링크 연결 버튼을 선택하시면<br />하이퍼링크 연결 속성창이 팝업으로 생성되고, 연결 내용 정보를 입력 후 확인을 선택하면 링크 연결이 생성됩니다.<br />=> 주소(필수 입력사항) : 링크 연결 주소<br />=> 연결방식(선택 입력사항) : 새창, 부모창, 현재창, 최상위창<br />=> 풍선도움말(선택 입력사항) : 링크 연결된 곳에 마우스를 움직이면 나타나는 풍선형태의 툴팁 도움말";
res_helpitem_MainDescription[3][1] = "하이퍼링크를 설정된 곳 일부분 또는 전체를 선택하면 하이퍼링크 제거 버튼이 활성화되며,<br />하이퍼링크 제거 버튼을 선택하면 기존에 설정된 연결 정보가 제거됩니다.";
res_helpitem_MainDescription[3][2] = "이미지(jpg, gif, png 파일)를 삽입하고자 하는 영역을 선택하시고 이미지 삽입/속성 버튼을 선택하시어<br />업로드를 진행 후 완료가 되면 편집창에 해당 이미지가 삽입됩니다.<br />(이미지를 선택하시고 이미지 삽입/속성 버튼을 선택하시면 이미지 속성창 팝업이 생성됩니다)";
res_helpitem_MainDescription[3][3] = "이미지를 선택하시고 이미지 삽입/속성 버튼을 선택하시면 이미지 속성창 팝업이 생성됩니다<br />생성된 팝업창에서 이미지의 크기,높이,테두리 등의 속성을 설정하실 수 있습니다<br />=> 주소URL(필수 입력사항) : 이미지 연결 주소<br />=> 풍선도움말(선택 입력사항) : 이미지에 마우스를 움직이면 나타나는 풍선형태의 툴팁 도움말<br />=> 크기,높이,테두리 설정(선택 입력사항)";
res_helpitem_MainDescription[3][4] = "플래시(swf 파일)를 삽입하고자 하는 영역을 선택하시고 플래시 삽입/속성 버튼을 선택하시어<br />업로드를 진행 후 완료가 되면 편집창에 해당 플래시가 삽입됩니다.<br />(플래시를 선택하시고 플래시 삽입/속성 버튼을 선택하시면 플래시 속성창 팝업이 생성됩니다)";
res_helpitem_MainDescription[3][5] = "플래시를 선택하시고 플래시 삽입/속성 버튼을 선택하시면 플래시 속성창 팝업이 생성됩니다<br />생성된 팝업창에서 플래시의 너비,높이,테두리 등의 속성을 설정하실 수 있습니다<br />=> 주소URL(필수 입력사항) : 플래시 연결 주소<br />=> 너비,높이(선택 입력사항)<br />=> 정렬방식(선택 입력사항) : 플래시가 설정된 위치에서 왼쪽, 가운데, 오른쪽 등 정렬방식 설정<br />=> 테두리,수평/수직 간격(선택 입력사항) : 수평/수직은 여백 공간의 설정";
res_helpitem_MainDescription[3][6] = "동영상(wmv 파일)를 삽입하고자 하는 영역을 선택하시고 동영상 삽입/속성 버튼을 선택하시어<br />업로드를 진행 후 완료가 되면 편집창에 해당 동영상이 삽입됩니다.<br />(동영상를 선택하시고 동영상 삽입/속성 버튼을 선택하시면 동영상 속성창 팝업이 생성됩니다)";
res_helpitem_MainDescription[3][7] = "동영상을 선택하시고 동영상 삽입/속성 버튼을 선택하시면 동영상 속성창 팝업이 생성됩니다<br />생성된 팝업창에서 동영상의 너비,높이,플레이어 속성 등을 설정하실 수 있습니다<br />=> 주소URL(필수 입력사항) : 동영상 연결 주소<br />=> 너비,높이(선택 입력사항)<br />=> 플레이어 속성(선택 입력사항) : 도구바 보이기 여부, 재생 상태 보이기 여부";
res_helpitem_MainDescription[3][8] = "특수문자를 삽입하고자 하는 영역을 선택하고 특수문자 드랍다운 버튼을 선택하시어 원하시는 특수문자를 선택하면<br />해당 영역에 특수문자가 삽입됩니다.";
res_helpitem_MainDescription[3][9] = "편집영역에 배경색을 적용하고자 하는 경우 문서배경색 드랍다운 버튼을 선택하시어 원하시는 색상을 선택하면<br />편집영역에 배경색이 적용됩니다.";
res_helpitem_MainDescription[3][10] = "편집영역에 배경이미지을 적용하고자 하는 경우 배경이미지 버튼을 선택하여 해당 내용을 적용합니다.";
res_helpitem_MainDescription[3][11] = "문서 템플릿을 삽입하고자 하는 영역을 선택하고 문서템플릿 버튼을 선택하여 해당 내용을 적용합니다.";

res_helpitem_MainDescription[4][0] = "메뉴의 도움말->제품도움말을 선택하시면 이노디터 제품 사용 도움말 팝업창이 생성됩니다.";
res_helpitem_MainDescription[4][1] = "메뉴의 도움말->제품정보를 선택하시면 이노디터 제품 정보 및 업데이트 날짜를 확인하실 수 있습니다.";

res_helpitem_SubDescription_1[0] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='100' align='center' class='outline'><b>크기설정</b></td><td width='220' align='center' class='outline'>너비와 높이를 설정하여 선택한<br />테이블의 전체 크기를 설정합니다.</td></tr><tr><td align='center' class='outline'><b>레이아웃</b></td><td align='center' class='outline'>테이블이 놓여질 위치를 설정합니다<br />테이블을 포함하고 있는 부모객체에<br />상대적으로 놓여질 위치를 설정하며,<br />셀안의 내용이 정렬될 위치는 셀속성의<br />가로/세로 정렬에서 설정합니다.</td></tr><tr><td align='center' class='outline'><b>테두리적용설정</b></td><td align='center' class='outline'>표 속성 세부(1) 참조</td></tr><tr><td align='center' class='outline'><b>테두리 설정</b></td><td align='center' class='outline'>표 속성 세부(2) 참조</td></tr><tr><td align='center' class='outline'><b>배경색</b></td><td align='center' class='outline'>우측의 색상버튼을 선택 후 적용하고자<br />하는 색상을 선택하면 테이블의 배경색이<br />적용됩니다. 셀 안의 배경색이 따로 지정된<br />경우 셀 배경색이 우선 표시됩니다.</td></tr><tr><td align='center' class='outline'><b>하이라이트색...</b></td><td align='center' class='outline'>표 속성 세부(3) 참조</td></tr><tr><td align='center' class='outline'><b>셀 간격/여백</b></td><td align='center' class='outline'>표 속성 세부(4) 참조</td></tr><tr><td align='center' class='outline'><b>미리보기</b></td><td align='center' class='outline'>표 속성을 변경하는 경우 설정된 값으로<br />보여지게 될 테이블 형태를 적용이전에<br />미리보기를 지원합니다.</td></tr></table>";
res_helpitem_SubDescription_1[1] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='80' align='center' class='outline'><b>테두리<br />합치기</b></td><td width='560' align='center' class='outline'>테이블 외부 테두리선과 셀 테두리의 색을 겹쳐 보이도록 할 것인지의 여부를 결정합니다.<br /><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td colspan='2' align='center' class='outline'>셀 간격 : 0</td><td colspan='2' align='center' class='outline'>셀 간격 : 1</td><td colspan='2' align='center' class='outline'>셀 간격 : 4</td></tr><tr><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_1.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_2.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_3.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_4.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_5.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_6.gif' alt='' /></td></tr><tr><td align='center' class='outline'>적용됨(Y)</td><td align='center' class='outline'>적용안됨(N)</td><td align='center' class='outline'>적용됨(Y)</td><td align='center' class='outline'>적용안됨(N)</td><td align='center' class='outline'>적용됨(Y)</td><td align='center' class='outline'>적용안됨(N)</td></tr></table></td></tr><tr><td align='center' class='outline'><b>셀 동시<br />적용</b></td><td align='center' class='outline'>테이블 테두리선과 셀 테두리에 선택된 테두리 속성을 동시에 적용할 지의 여부를 결정합니다.<br /><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td colspan='2' align='center' class='outline'>셀 간격 : 0</td><td colspan='2' align='center' class='outline'>셀 간격 : 1</td><td colspan='2' align='center' class='outline'>셀 간격 : 4</td></tr><tr><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_7.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_8.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_9.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_10.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_11.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_12.gif' alt='' /></td></tr><tr><td align='center' class='outline'>적용됨(Y)</td><td align='center' class='outline'>적용안됨(N)</td><td align='center' class='outline'>적용됨(Y)</td><td align='center' class='outline'>적용안됨(N)</td><td align='center' class='outline'>적용됨(Y)</td><td align='center' class='outline'>적용안됨(N)</td></tr></table></td></tr></table>";
res_helpitem_SubDescription_1[2] = "<table border='0' cellpadding='0' cellspacing='0' width='100%'><tr><td colspan='4' height='3'></td></tr><tr><td width='10'></td><td align='center'><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='80' align='center' class='outline'><b>개별적용<br />여부</b></td><td width='560' align='center' class='outline'>테이블 테두리선의 Left, Top, Right, Bottom 개별 여부 적용를 설정합니다.<br />개별 적용이 선택된 경우 각각의 테두리 형태, 크기, 색상을 설정할 수 있습니다.</td></tr><tr><td align='center' class='outline'><b>형태/크기</b></td><td align='center' class='outline'>테이블 테두리선 형태와 크기를 설정합니다. double형 또는 3D 형태의 테두리인 경우<br />크기가 3 이상이여야 차이점이 표시됩니다.<br /><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_1.gif' alt='' /></td><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_2.gif' alt='' /></td><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_3.gif' alt='' /></td><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_4.gif' alt='' /></td></tr><tr><td align='center' class='outline'>solid / 1px</td><td align='center' class='outline'>dotted / 1px</td><td align='center' class='outline'>dashed / 1px</td><td align='center' class='outline'>double / 4px</td></tr><tr><td align='center' class='outline'><img src='./image/help_main_1_11_sub_5.gif' alt='' /></td><td align='center' class='outline'><img src='./image/help_main_1_11_sub_6.gif' alt='' /></td><td align='center' class='outline'><img src='./image/help_main_1_11_sub_7.gif' alt='' /></td><td align='center' class='outline'><img src='./image/help_main_1_11_sub_8.gif' alt='' /></td></tr><tr><td align='center' class='outline'>groove(3D) / 4px</td><td align='center' class='outline'>ridge(3D) / 4px</td><td align='center' class='outline'>inset(3D) / 4px</td><td align='center' class='outline'>outset(3D) / 4px</td></tr></table></td></tr><tr><td width='80' align='center' class='outline'><b>테두리색</b></td><td width='560' align='center' class='outline'>테이블 테두리에 대한 색상을 지정합니다.</td></tr></table></td><td width='10'></td></tr><tr><td colspan='4' height='3'></td></tr></table>";
res_helpitem_SubDescription_1[3] = '<table cellspacing="0" cellpadding="0" style="border-collapse:collapse"><tr><td width="80" align="center" class="outline"><b>셀 간격</b></td><td width="560" align="center" class="outline"><table cellspacing="0" cellpadding="0" style="border-collapse:collapse"><tr><td width="100" align="center" class="outline"><img src="./image/help_main_1_12_sub_1.gif" alt="" /></td><td width="100" align="center" class="outline"><img src="./image/help_main_1_12_sub_2.gif" alt="" /></td><td width="100" align="center" class="outline"><img src="./image/help_main_1_12_sub_3.gif" alt="" /></td><td width="100" align="center" class="outline"><img src="./image/help_main_1_12_sub_4.gif" alt="" /></td><td width="100" align="center" class="outline"><img src="./image/help_main_1_12_sub_5.gif" alt="" /></td></tr><tr><td align="center" class="outline">간격 : 0<br />겹쳐보이기 : Y<br />테두리 외곽선 : 1</td><td align="center" class="outline">간격 : 2<br />겹쳐보이기 : Y<br />테두리 외곽선 : 1</td><td align="center" class="outline">간격 : 2<br />겹쳐보이기 : N<br />테두리 외곽선 : 1</td><td align="center" class="outline">간격 : 6<br />겹쳐보이기 : Y<br />테두리 외곽선 : 1</td><td align="center" class="outline">간격 : 6<br />겹쳐보이기 : N<br />테두리 외곽선 : 0</td></tr></table></td></tr><tr><td align="center" class="outline"><b>셀 여백</b></td><td align="center" class="outline">셀 안의 내용이 테두리로부터 떨어져 보여질 간격을 설정합니다.</td></tr></table>';
res_helpitem_SubDescription_1[4] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='100' align='center' class='outline'><b>셀 선택</b></td><td width='220' align='center' class='outline'>셀 속성창 생성 이전에 테이블의<br />선택된 셀의 정보가 표시됩니다.<br />선택된 셀을 클릭하면 선택 또는<br />선택해제가 되며, 다른 셀도 동일한<br />방법으로 선택할 수 있습니다.<br />테이블의 미리보기와 동일하게<br />셀 속성의 정보를 수정시 적용이전에<br />미리보기를 지원합니다.</td></tr><tr><td align='center' class='outline'><b>테이블 테두리<br />적용 여부</b></td><td align='center' class='outline'>각각의 셀 별로 테두리 형태, 크기,<br />색상 및 배경색을 지정하는 경우<br />테이블 속성에 영향을 받는 부분이<br />발생되며, 이런 경우 테이블 속성을<br />제거하여 셀 속성을 지정할 수 있습니다.<br />(테이블 속성에서의 동일한 설정은<br />테두리 합치기 - 해제, 크기 - 0,<br />색상 - 제거 로 설정한 것과 동일)</td></tr><tr><td align='center' class='outline'><b>셀 배경색</b></td><td align='center' class='outline'>우측의 색상버튼을 선택 후 적용하고자<br />하는 색상을 선택하면 셀의 배경색이<br />적용됩니다. 셀 안의 배경색 설정이 없는<br />경우 테이블 배경색이 표시됩니다.</td></tr><tr><td align='center' class='outline'><b>셀 테두리 설정</b></td><td align='center' class='outline'>셀 속성 세부(1) 참조</td></tr></table>";
res_helpitem_SubDescription_1[5] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='90' align='center' class='outline'><b>테두리 형태</b></td><td width='220' align='center' class='outline'>셀의 테두리 형태를 설정<br />(테이블 테두리 형태와 동일한 형태<br />- 표 속성 세부(2) 참조)</td></tr><tr><td align='center' class='outline'><b>테두리 크기</b></td><td align='center' class='outline'>셀의 테두리 크기를 설정<br />(테이블 테두리 크기와 동일한 형태<br />- 표 속성 세부(2) 참조)</td></tr><tr><td align='center' class='outline'><b>테두리색</b></td><td align='center' class='outline'>셀의 테두리에 적용될 색상을 선택<br /></td></tr><tr><td align='center' class='outline'><b>테두리 선택</b></td><td align='center' class='outline'>테두리의 형태, 크기, 색상를 선택하신<br />후 테두리 선택의 상,하,좌,우의 각<br />화살표를 선택하시면 테두리의 표시<br />여부가 설정됩니다.</td></tr></table>";
res_helpitem_SubDescription_1[6] = "셀 테두리 적용 예";
res_helpitem_SubDescription_1[7] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='90' align='center' class='outline'><b>셀 선택</b></td><td width='220' align='center' class='outline'>셀 속성창 생성 이전에 테이블의<br />선택된 셀의 정보가 표시됩니다.<br />선택된 셀을 클릭하면 선택 또는<br />선택해제가 되며, 다른 셀도 동일한<br />방법으로 선택할 수 있습니다.</td></tr><tr><td align='center' class='outline'><b>셀 크기설정</b></td><td align='center' class='outline'>선택된 셀에 대한 너비, 높이를<br />설정합니다. 별도의 설정이 없는 경우<br />셀 크기를 설정하지 않으며, 너비만<br />따로 또는 높이만 따로 설정할 수<br />있습니다.<br /></td></tr><tr><td align='center' class='outline'><b>셀 레이아웃</b></td><td align='center' class='outline'>선택된 셀에 대한 가로와 세로의<br />정렬을 설정합니다.<br />(가로 - 왼쪽, 가운데, 오른쪽<br />세로 - 위쪽, 가운데, 아래쪽)</td></tr></table>";
