var res_helpitem = new Array();
var res_helpitem_MainTitle_Sub = new Array();
var res_helpitem_MainDescription = new Array();
var res_helpitem_SubDescription_1 = new Array();

res_helpitem[0] = new Array();
res_helpitem[1] = new Array();
res_helpitem[2] = new Array();
res_helpitem[3] = new Array();
res_helpitem[4] = new Array();

res_helpitem_MainDescription[0] = new Array();
res_helpitem_MainDescription[1] = new Array();
res_helpitem_MainDescription[2] = new Array();
res_helpitem_MainDescription[3] = new Array();
res_helpitem_MainDescription[4] = new Array();


res_helpitem[0][0] = "字体";
res_helpitem[0][1] = "文字大小";
res_helpitem[0][2] = "加粗";
res_helpitem[0][3] = "斜体";
res_helpitem[0][4] = "下划线";
res_helpitem[0][5] = "前景色";
res_helpitem[0][6] = "背景色";
res_helpitem[0][7] = "居左";
res_helpitem[0][8] = "居中";
res_helpitem[0][9] = "居右";
res_helpitem[0][10] = "加序号";
res_helpitem[0][11] = "句首序号";
res_helpitem[0][12] = "字距";
res_helpitem[0][13] = "行距";
res_helpitem[0][14] = "删除线";
res_helpitem[0][15] = "下添字";
res_helpitem[0][16] = "上添字";
res_helpitem[0][17] = "缩出";
res_helpitem[0][18] = "缩进";

res_helpitem[1][0] = "创建表格";
res_helpitem[1][1] = "加行";
res_helpitem[1][2] = "删行";
res_helpitem[1][3] = "加列";
res_helpitem[1][4] = "删列";
res_helpitem[1][5] = "单元格合并";
res_helpitem[1][6] = "分行";
res_helpitem[1][7] = "分列";
res_helpitem[1][8] = "表格模板";
res_helpitem[1][9] = "表格属性概要";
res_helpitem[1][10] = "表格详细属性(1)";
res_helpitem[1][11] = "表格详细属性(2)";
res_helpitem[1][12] = "表格详细属性(3)";
res_helpitem[1][13] = "单元格属性概要";
res_helpitem[1][14] = "<span style='font-size:7pt;'>单元格属性概要(1)</span>";
res_helpitem[1][15] = "<span style='font-size:7pt;'>单元格属性概要(2)</span>";

res_helpitem[2][0] = "剪切";
res_helpitem[2][1] = "复制";
res_helpitem[2][2] = "粘帖";
res_helpitem[2][3] = "删除";
res_helpitem[2][4] = "全选";

res_helpitem[3][0] = "快捷链接";
res_helpitem[3][1] = "删除链接";
res_helpitem[3][2] = "插入图片";
res_helpitem[3][3] = "图片属性";
res_helpitem[3][4] = "Flash 插入";
res_helpitem[3][5] = "Flash 属性";
res_helpitem[3][6] = "视频插入";
res_helpitem[3][7] = "视频属性";
res_helpitem[3][8] = "特殊字符";
res_helpitem[3][9] = "文档背景色";
res_helpitem[3][10] = "文档背景图像";
res_helpitem[3][11] = "文档模板";

res_helpitem[4][0] = "产品帮助";
res_helpitem[4][1] = "产品信息";

res_helpitem_MainTitle_Sub[0] = "";
res_helpitem_MainTitle_Sub[1] = "";
res_helpitem_MainTitle_Sub[2] = "";
res_helpitem_MainTitle_Sub[3] = "";
res_helpitem_MainTitle_Sub[4] = "";
res_helpitem_MainTitle_Sub[5] = "";
res_helpitem_MainTitle_Sub[6] = "";
res_helpitem_MainTitle_Sub[7] = "";
res_helpitem_MainTitle_Sub[8] = "";
res_helpitem_MainTitle_Sub[9] = "";
res_helpitem_MainTitle_Sub[10] = " - 表格边框适用设置";
res_helpitem_MainTitle_Sub[11] = " - 表格边框设置";
res_helpitem_MainTitle_Sub[12] = " - 表格单元格间隔/空白设置";
res_helpitem_MainTitle_Sub[13] = " - 边框/颜色";
res_helpitem_MainTitle_Sub[14] = " - 边框 设置";
res_helpitem_MainTitle_Sub[15] = " - 大小/排列";

res_helpitem_MainDescription[0][0] = "将需要改变的区域选好后, 在字体下拉框里选择需要的字体, 可变成相应的字体.";
res_helpitem_MainDescription[0][1] = "将需要改变的区域选好后, 在文字大小下拉框里选择适当的大小, 可变成相应的大小.";
res_helpitem_MainDescription[0][2] = "将需要改变的区域选好后, 选择加粗键, 即可加粗.<br />如果文字已经是加粗状态, 重新点击加粗键, 会回到原来的状态.";
res_helpitem_MainDescription[0][3] = "将需要改变的区域选好后, 选择斜体键, 即可让字变成斜体字.<br />如果文字已经是斜体状态, 重新点击斜体键, 会回到原来的状态.";
res_helpitem_MainDescription[0][4] = "将需要改变的区域选好后, 选择下划线键, 即可在字下面显示下划线.<br />如果文字已经有下划线, 重新点击下划线键, 会回到原来的状态.";
res_helpitem_MainDescription[0][5] = "将需要改变的区域选好后, 点击前景色下拉框, 选择所需的颜色, 前景色即可变成所选颜色.";
res_helpitem_MainDescription[0][6] = "将需要改变的区域选好后, 点击背景色下拉框, 选择所需的颜色, 背景色即可变成所选颜色.";
res_helpitem_MainDescription[0][7] = "选择需要对齐的区域, 点击居左键, 文字将全部以左基准对齐显示.";
res_helpitem_MainDescription[0][8] = "选择需要对齐的区域, 点击居中键, 文字将全部以中间基准对齐显示.";
res_helpitem_MainDescription[0][9] = "选择需要对齐的区域, 点击居右键, 文字将全部以右基准对齐显示.";
res_helpitem_MainDescription[0][10] = "需要在文字前端自动生成序号, 则选择相应区域后, 选择加序号键, 即可在文字前加序号.<br />如果已经有序号, 点击加序号键, 则回到原来的状态.";
res_helpitem_MainDescription[0][11] = "需要在文字前端自动生成句首序号, 则选择相应区域后, 选择句首序号键, 即可在文字前生成句首序号.<br />如果已经有句首序号, 点击句首序号键, 则回到原来的状态.";
res_helpitem_MainDescription[0][12] = "选择需要变更的区域后, 选择字距键的下拉框, 选择适当的字距, 字距则变成所选的字距.";
res_helpitem_MainDescription[0][13] = "选择需要变更的区域后, 选择行距键的下拉框, 选择适当的行距, 行距则变成所选的行距.";
res_helpitem_MainDescription[0][14] = "选择需要变更的区域后, 选择删除线键时, 文字的中间部分会显示删除线条.<br />如果文字已经加油删除线, 点击删除线则原来的删除线消失回到原来的状态.";
res_helpitem_MainDescription[0][15] = "选择需要变更的区域后, 选择下添字键时, 文字的下端会生成添加字, 完成下添字.<br />如果已经有下添字, 点击下添字键则回到原来的状态.";
res_helpitem_MainDescription[0][16] = "选择需要变更的区域后, 选择上添字键时, 文字的上端会生成添加字, 完成上添字.<br />如果已经有上添字, 点击上添字键则回到原来的状态.";
res_helpitem_MainDescription[0][17] = "选择需要变更的区域后, 点击缩出键时, 文字前面不会留有空白, 紧贴着显示文字.";
res_helpitem_MainDescription[0][18] = "选择需要变更的区域后, 点击缩进键时, 文字前面会留有一定的空白后再显示文字.";

res_helpitem_MainDescription[1][0] = "选择表格生成下拉框时, 会出现选择表格行X列的窗口, 用鼠标移至所需的行列位置后选择, 则会在编辑窗口生成表格.";
res_helpitem_MainDescription[1][1] = "选择单元格, 单行或多行, 加行键则显示激活状态, 点击加行键, 在前面生成跟所选区域一样多的行.";
res_helpitem_MainDescription[1][2] = "选择单行或多行, 删行键则显示激活状态, 点击删行键, 所选区域的行将被删除.";
res_helpitem_MainDescription[1][3] = "选择单元格, 单列或多重列, 加列键则显示激活状态, 点击加列键, 在前面生成跟所选区域一样多的列.";
res_helpitem_MainDescription[1][4] = "选择单列或多列, 删列键则显示激活状态, 点击删列键, 所选区域的列将被删除.";
res_helpitem_MainDescription[1][5] = "选择多重单元格后单元格, 合并键将显示激活状态, 点击单元格合并键, 所选区域可合并在一起.";
res_helpitem_MainDescription[1][6] = "选择多重单元格后如果可以分行, 分行键将显示激活状态, 点击分行键, 所选区域的行将分行处理.";
res_helpitem_MainDescription[1][7] = "选择多重单元格后如果可以分列, 分列键将显示激活状态, 点击分列键, 所选区域的列将分列处理.";
res_helpitem_MainDescription[1][8] = "选择要生成表格模板, 即可生成相应模式的表格.";
res_helpitem_MainDescription[1][9] = "选择表格的一部分单元格, 在菜单或弹出菜单中选择表格属性, 将会生成可设置详细属性的弹出窗,<br />并且可在弹出窗设置各属性的详细设置, 通过预览确认后可适用.";
res_helpitem_MainDescription[1][10] = "设置边框合并部分和同时适用单元格与否.";
res_helpitem_MainDescription[1][11] = "设置表格边框的形态, 大小, 颜色及 Left, Top, Right, Bottom分别适用与否";
res_helpitem_MainDescription[1][12] = "设置表格单元格间隔/空白. (单元格间隔 - cellspacing, 单元格空白 - cellpadding)<br />根据外框线合并与否及表格边框删除与否, 显示多种形态.";
res_helpitem_MainDescription[1][13] = "选择表格的一部分单元格, 在菜单或填出菜单中选择 单元格属性, 可生成设置详细属性的弹出窗,<br />并且可在弹出窗设置各属性相应的详细设置, 通过预览确认后可适用.";
res_helpitem_MainDescription[1][14] = "分别设置被选单元格边框的形态, 大小, 颜色, 显示与否.";
res_helpitem_MainDescription[1][15] = "选择表格的一部分单元格, 在菜单弹出菜单中选择 单元格属性, 可生成设置详细属性的弹出窗,<br />选择弹出窗的右上端大小/排列键, 可显示能设置大小和布局的详细设置窗.";

res_helpitem_MainDescription[2][0] = "选择需要剪切的区域后, 通过菜单的编辑->剪切, 键盘的(Ctrl+X)或弹出菜单中的剪切键, 可执行被选区域的剪切操作.";
res_helpitem_MainDescription[2][1] = "选择需要复制的区域后, 通过菜单的编辑->复制, 键盘的(Ctrl+C)或弹出菜单中的复制键, 可执行被选区域的复制操作.";
res_helpitem_MainDescription[2][2] = "选择需要黏贴的区域后, 通过菜单的编辑->黏贴, 键盘的(Ctrl+V)或弹出菜单中的黏贴键, 可执行被选区域的黏贴操作.";
res_helpitem_MainDescription[2][3] = "选择需要删除的区域后, 通过菜单的编辑->删除, 键盘的(Delete)或弹出菜单中的删除键, 可执行被选区域的删除操作.";
res_helpitem_MainDescription[2][4] = "需要选择整个区域时, 点击菜单中的编辑->全选 或者通过键盘的(Ctrl+A)执行全选操作";

res_helpitem_MainDescription[3][0] = "选择要执行快捷链接的区域, 点击快捷链接键, 以弹出窗的形式生成快捷链接属性窗口, 确认链接内容信息后,<br />点击确认键则生成 快捷链接<br />=> 地址(必填) : 快捷链接地址<br />=> 链接方式(选项) : 新窗口, 父母窗口, 当前窗口, 最上端窗口<br />=> 帮助(选项) : 把鼠标放在快捷链接处 移动时显示的气球状的帮助按钮";
res_helpitem_MainDescription[3][1] = "选择设置好快捷链接的一部分活着全体时, 删除链接将处于激活状态, 点击删除链接键, 可除去已经链接的信息";
res_helpitem_MainDescription[3][2] = "选择需要图像(jpg, gif, png 文档)区域后, 点击插入图片/属性键, 上传完毕后 相应图片会插入在编辑窗口上<br />(选择图像后再选择插入图片/属性键时 生成图片属性窗的弹出窗口)";
res_helpitem_MainDescription[3][3] = "选择图像后, 点击插入图片/属性键 即可生成图片属性弹出窗口.<br />在生成的弹出窗口可设置图像大小,高度,边框等属性.<br />=> 地址URL(必填) : 图片链接地址<br />=>  帮助(选项) : 把鼠标放在快捷链接的地方 移动时显示的气球状的帮助按钮<br />=> 大小,高度,边框 设置(选项)";
res_helpitem_MainDescription[3][4] = "选择需要插入Flash(swf 文档)的区域后, 选择Flash 插入/属性键, 上传文档, 完毕后在编辑窗口即可插入相应的Flash.<br />(选择Flash后选择 Flash 插入/属性键, 即可生成 Flash 属性弹出窗口)";
res_helpitem_MainDescription[3][5] = "选择Flash后点击 Flash 插入/属性键, 即可生成 Flash 属性弹出窗口.<br />可在生成的弹出窗口设置 Flash的宽度,高度,边框等属性.<br />=> 地址URL(必填) : Flash 链接地址<br />=> 宽度,高度(选项)<br />=> 排列方式(选项) : 在Flash 设置的位置设置 左边, 中间, 右边等排列方式<br />=> 边框,水平/垂直间隔(选项) : 设置水平/垂直的 空白空间";
res_helpitem_MainDescription[3][6] = "选择需要插入视频(wmv 文档)的区域, 点击视频插入/属性键, 上传文档, 完毕后在编辑窗口即可插入相应的视频.<br />(选择视频后选择视频插入/属性键, 即可生成 视频属性弹出窗口)";
res_helpitem_MainDescription[3][7] = "选择视频后点击视频插入/属性键, 即可生成视频属性弹出窗口.<br />在生成的弹出窗口可设置视频的宽度,高度,播放器属性等.<br />=> 地址URL(必填) : 视频链接地址<br />=> 宽度,高度(选项)<br />=> 播放器属性(选项) : 显示工具条与否, 显示播放状态与否";
res_helpitem_MainDescription[3][8] = "选择需要插入特殊字符的渔区, 点击特殊字符<br />下拉框, 选择相应的特殊字符, 即可在相应区域插入特殊字符.";
res_helpitem_MainDescription[3][9] = "想要在编辑区域适用背景色时, 点击文档背景色<br />下拉框后选择相应的颜色, 即可在编辑区域显示背景色.";
res_helpitem_MainDescription[3][10] = "想要在编辑区域适用背景图像时, 点击背景图像键, 选择图像后即可适用相应内容.";
res_helpitem_MainDescription[3][11] = "选择需要插入文档模板的区域后<br />点击文档模板键, 适用相应内容即可.";

res_helpitem_MainDescription[4][0] = "选择菜单的帮助->产品帮助, 可生成INNODITOR 产品使用帮助窗口.";
res_helpitem_MainDescription[4][1] = "选择菜单的帮助->产品信息, 可确认INNODITOR 产品信息及更新日期.";

res_helpitem_SubDescription_1[0] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='100' align='center' class='outline'><b>大小设置</b></td><td width='220' align='center' class='outline'>设置宽度和高度,<br />设置被选表格的整体大小</td></tr><tr><td align='center' class='outline'><b>布局</b></td><td align='center' class='outline'>设置表格摆放位置.<br />设置包含表格的父母客体中相对位置,<br />单元格的内容需要排列的位置<br />在单元格属性的横向/纵向排列中设置.</td></tr><tr><td align='center' class='outline'><b>边框适用设置</b></td><td align='center' class='outline'>参考表格详细属性(1)</td></tr><tr><td align='center' class='outline'><b>边框设置</b></td><td align='center' class='outline'>参考表格详细属性(2)</td></tr><tr><td align='center' class='outline'><b>背景色</b></td><td align='center' class='outline'>选择右侧的颜色案件后选择需要的颜色,<br />表格则会显示背景色.<br />单元格里的背景色如有特别指定,<br />单元格背景色优先显示.</td></tr><tr><td align='center' class='outline'><b>荧光笔颜色...</b></td><td align='center' class='outline'>参考表格详细属性(3)</td></tr><tr><td align='center' class='outline'><b>单元格间隔/空白</b></td><td align='center' class='outline'>参考表格详细属性(4)</td></tr><tr><td align='center' class='outline'><b>预览</b></td><td align='center' class='outline'>要变更表格属性时,<br />在显示变更后的值之前<br />可以先浏览.</td></tr></table>";
res_helpitem_SubDescription_1[1] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='80' align='center' class='outline'><b>边框合并</b></td><td width='560' align='center' class='outline'>决定表格外边框线和单元格边框颜色是否重叠显示<br /><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td colspan='2' align='center' class='outline'>单元格间隔 : 0</td><td colspan='2' align='center' class='outline'>单元格间隔 : 1</td><td colspan='2' align='center' class='outline'>单元格间隔 : 4</td></tr><tr><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_1.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_2.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_3.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_4.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_5.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_6.gif' alt='' /></td></tr><tr><td align='center' class='outline'>适用(Y)</td><td align='center' class='outline'>不适用(N)</td><td align='center' class='outline'>适用(Y)</td><td align='center' class='outline'>不适用(N)</td><td align='center' class='outline'>适用(Y)</td><td align='center' class='outline'>不适用(N)</td></tr></table></td></tr><tr><td align='center' class='outline'><b>同时适用单元格</b></td><td align='center' class='outline'>决定表格边框线和单元格边框选择的边框属性是否同时适用.<br /><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td colspan='2' align='center' class='outline'>单元格间隔 : 0</td><td colspan='2' align='center' class='outline'>单元格间隔 : 1</td><td colspan='2' align='center' class='outline'>单元格间隔 : 4</td></tr><tr><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_7.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_8.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_9.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_10.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_11.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_12.gif' alt='' /></td></tr><tr><td align='center' class='outline'>适用(Y)</td><td align='center' class='outline'>不适用(N)</td><td align='center' class='outline'>适用(Y)</td><td align='center' class='outline'>不适用(N)</td><td align='center' class='outline'>适用(Y)</td><td align='center' class='outline'>不适用(N)</td></tr></table></td></tr></table>";
res_helpitem_SubDescription_1[2] = "<table border='0' cellpadding='0' cellspacing='0' width='100%'><tr><td colspan='4' height='3'></td></tr><tr><td width='10'></td><td align='center'><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='80' align='center' class='outline'><b>个别适用与否</b></td><td width='560' align='center' class='outline'>设置表格边框线的 Left, Top, Right, Bottom 分别适用与否.<br />可分别设置分别适用的各边框形态, 大小, 颜色</td></tr><tr><td align='center' class='outline'><b>形态/大小</b></td><td align='center' class='outline'>设置表格边框线形态和大小. 双线或3D形态的边框应满足大小3以上,<br />才可在表格上显示差异.<br /><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_1.gif' alt='' /></td><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_2.gif' alt='' /></td><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_3.gif' alt='' /></td><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_4.gif' alt='' /></td></tr><tr><td align='center' class='outline'>solid / 1px</td><td align='center' class='outline'>dotted / 1px</td><td align='center' class='outline'>dashed / 1px</td><td align='center' class='outline'>double / 4px</td></tr><tr><td align='center' class='outline'><img src='./image/help_main_1_11_sub_5.gif' alt='' /></td><td align='center' class='outline'><img src='./image/help_main_1_11_sub_6.gif' alt='' /></td><td align='center' class='outline'><img src='./image/help_main_1_11_sub_7.gif' alt='' /></td><td align='center' class='outline'><img src='./image/help_main_1_11_sub_8.gif' alt='' /></td></tr><tr><td align='center' class='outline'>groove(3D) / 4px</td><td align='center' class='outline'>ridge(3D) / 4px</td><td align='center' class='outline'>inset(3D) / 4px</td><td align='center' class='outline'>outset(3D) / 4px</td></tr></table></td></tr><tr><td width='80' align='center' class='outline'><b>边框色</b></td><td width='560' align='center' class='outline'>指定表格边框的颜色</td></tr></table></td><td width='10'></td></tr><tr><td colspan='4' height='3'></td></tr></table>";
res_helpitem_SubDescription_1[3] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='80' align='center' class='outline'><b>单元格间隔</b></td><td width='560' align='center' class='outline'><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_1.gif' alt='' /></td><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_2.gif' alt='' /></td><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_3.gif' alt='' /></td><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_4.gif' alt='' /></td><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_5.gif' alt='' /></td></tr><tr><td align='center' class='outline'>间隔 : 0<br />重叠显示 : Y<br />边框外框线 : 1</td><td align='center' class='outline'>间隔 : 2<br />重叠显示 : Y<br />边框外框线 : 1</td><td align='center' class='outline'>间隔 : 2<br />重叠显示 : N<br />边框外框线 : 1</td><td align='center' class='outline'>间隔 : 6<br />重叠显示 : Y<br />边框外框线 : 1</td><td align='center' class='outline'>间隔 : 6<br />重叠显示 : N<br />边框外框线 : 0</td></tr></table></td></tr><tr><td align='center' class='outline'><b>单元格空白</b></td><td align='center' class='outline'>单元格的内容显得离边框较远时设置间隔.</td></tr></table>";
res_helpitem_SubDescription_1[4] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='100' align='center' class='outline'><b>单元格选项</b></td><td width='220' align='center' class='outline'>单元格属性窗生成前显示以前表格被选单元格的信息.<br />点击被选单元格, 可选择或解除选择,<br />其他单元格也可通过同样的方法选择.<br />跟表格预览功能一样,<br />修改单元格属性信息时<br />适用前可预览.</td></tr><tr><td align='center' class='outline'><b>表格边框适用<br />与否</b></td><td align='center' class='outline'>按照各个单元格设置边框形态,<br />大小, 颜色及背景色时<br />会发生影响表格属性的部分,<br />此时应除去表格属性, 指定单元格属性<br />(跟表格属性同样的设置跟<br />边框合并 - 解除, 大小 - 0,<br />颜色 - 清楚时的设置一样)</td></tr><tr><td align='center' class='outline'><b>单元格背景色</b></td><td align='center' class='outline'>选择右侧的颜色键后, 选择需要的颜色,<br />选择之后单元格则适用背景色.<br />未设置单元格背景色时显示表格背景色.</td></tr><tr><td align='center' class='outline'><b>单元格边框设置</b></td><td align='center' class='outline'>参考单元格详细属性(1)</td></tr></table>";
res_helpitem_SubDescription_1[5] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='90' align='center' class='outline'><b>边框形态</b></td><td width='220' align='center' class='outline'>设置单元格边框形态<br />(跟表格边框形态一样<br />- 参考表格详细属性(2))</td></tr><tr><td align='center' class='outline'><b>边框大小</b></td><td align='center' class='outline'>设置单元格边框大小<br />(跟表格边框大小一样<br />- 参考表格详细属性(2))</td></tr><tr><td align='center' class='outline'><b>边框色</b></td><td align='center' class='outline'>选择单元格边框适用的颜色<br /></td></tr><tr><td align='center' class='outline'><b>边框选择</b></td><td align='center' class='outline'>选择边框的形态,<br />大小, 颜色后, 选择边框的<br />上,下,左,右的各个箭头,<br />设置是否显示边框.</td></tr></table>";
res_helpitem_SubDescription_1[6] = "<b>单元格边框适用例子</b>";
res_helpitem_SubDescription_1[7] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='90' align='center' class='outline'><b>单元格选项</b></td><td width='220' align='center' class='outline'>单元格属性窗生成前显示表格被选单元格的信息<br />点击被选单元格, 可选择或解除选择,<br />其他单元格也可以通过同样的方法选择.</td></tr><tr><td align='center' class='outline'><b>单元格大小设置</b></td><td align='center' class='outline'>可设置被选单元格的宽度, 高度.<br />无需特别设置时,<br />可以不设置单元格的大小,<br />仅设置宽度或高度.<br /></td></tr><tr><td align='center' class='outline'><b>单元格布局</b></td><td align='center' class='outline'>设置被选单元格的横竖排列<br />(横 - 左边, 中间, 右边<br />竖 - 上边, 中间, 下边)</td></tr></table>";
