DROP TABLE KETMOLDCHANGEPLANLINE;

CREATE TABLE KETMOLDCHANGEPLANLINE (
      SCHEDULEID   VARCHAR2(100 BYTE)
       ,LINEORDER    NUMBER
       ,USERID       VARCHAR2(100 BYTE)
       ,USERNAME     VARCHAR2(100 BYTE)
       ,PLANCOMMENT  VARCHAR2(1000 BYTE)
       ,CREATEDATE   DATE
       ,MODIFYDATE   DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 98304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "KET_DATA" ;

COMMENT ON COLUMN KETMOLDCHANGEPLANLINE.SCHEDULEID IS '양산금형 ID';
COMMENT ON COLUMN KETMOLDCHANGEPLANLINE.LINEORDER IS '양산금형 Comment 순서';
COMMENT ON COLUMN KETMOLDCHANGEPLANLINE.USERID IS '등록자 ID';
COMMENT ON COLUMN KETMOLDCHANGEPLANLINE.USERNAME IS '등록자명';
COMMENT ON COLUMN KETMOLDCHANGEPLANLINE.PLANCOMMENT IS 'COMMENT';
COMMENT ON COLUMN KETMOLDCHANGEPLANLINE.CREATEDATE IS '등록일';
COMMENT ON COLUMN KETMOLDCHANGEPLANLINE.MODIFYDATE IS '수정일';