var res_helpitem = new Array();
var res_helpitem_MainTitle_Sub = new Array();
var res_helpitem_MainDescription = new Array();
var res_helpitem_SubDescription_1 = new Array();

res_helpitem[0] = new Array();
res_helpitem[1] = new Array();
res_helpitem[2] = new Array();
res_helpitem[3] = new Array();
res_helpitem[4] = new Array();

res_helpitem_MainDescription[0] = new Array();
res_helpitem_MainDescription[1] = new Array();
res_helpitem_MainDescription[2] = new Array();
res_helpitem_MainDescription[3] = new Array();
res_helpitem_MainDescription[4] = new Array();


res_helpitem[0][0] = "Font";
res_helpitem[0][1] = "Size";
res_helpitem[0][2] = "Bold";
res_helpitem[0][3] = "Italic";
res_helpitem[0][4] = "Underline";
res_helpitem[0][5] = "ForeColor";
res_helpitem[0][6] = "BackColor";
res_helpitem[0][7] = "Justify Left";
res_helpitem[0][8] = "Justify Center";
res_helpitem[0][9] = "Justify Right";
res_helpitem[0][10] = "OrderList";
res_helpitem[0][11] = "UnorderList";
res_helpitem[0][12] = "Letter Spacing";
res_helpitem[0][13] = "Line Height";
res_helpitem[0][14] = "Strike";
res_helpitem[0][15] = "Sub Script";
res_helpitem[0][16] = "Super Script";
res_helpitem[0][17] = "Outdent";
res_helpitem[0][18] = "Indent";

res_helpitem[1][0] = "Create Table";
res_helpitem[1][1] = "Insert Row";
res_helpitem[1][2] = "Delete Row";
res_helpitem[1][3] = "Insert Col";
res_helpitem[1][4] = "Delete Col";
res_helpitem[1][5] = "Merge Cell";
res_helpitem[1][6] = "Split Row";
res_helpitem[1][7] = "Split Col";
res_helpitem[1][8] = "Table Templete";
res_helpitem[1][9] = "Table Property";
res_helpitem[1][10] = "Table Property(1)";
res_helpitem[1][11] = "Table Property(2)";
res_helpitem[1][12] = "Table Property(3)";
res_helpitem[1][13] = "Cell Property";
res_helpitem[1][14] = "Cell Property(1)";
res_helpitem[1][15] = "Cell Property(2)";

res_helpitem[2][0] = "Cut";
res_helpitem[2][1] = "Copy";
res_helpitem[2][2] = "Paste";
res_helpitem[2][3] = "Delete";
res_helpitem[2][4] = "Select All";

res_helpitem[3][0] = "Create Link";
res_helpitem[3][1] = "Remove Link";
res_helpitem[3][2] = "Insert Image";
res_helpitem[3][3] = "Image Property";
res_helpitem[3][4] = "Insert Flash";
res_helpitem[3][5] = "Flash Property";
res_helpitem[3][6] = "Insert Media";
res_helpitem[3][7] = "Media Property";
res_helpitem[3][8] = "SpecialCharacter";
res_helpitem[3][9] = "Doc. BackColor";
res_helpitem[3][10] = "Doc. Image";
res_helpitem[3][11] = "Doc. Templete";

res_helpitem[4][0] = "Help";
res_helpitem[4][1] = "Information";

res_helpitem_MainTitle_Sub[0] = "";
res_helpitem_MainTitle_Sub[1] = "";
res_helpitem_MainTitle_Sub[2] = "";
res_helpitem_MainTitle_Sub[3] = "";
res_helpitem_MainTitle_Sub[4] = "";
res_helpitem_MainTitle_Sub[5] = "";
res_helpitem_MainTitle_Sub[6] = "";
res_helpitem_MainTitle_Sub[7] = "";
res_helpitem_MainTitle_Sub[8] = "";
res_helpitem_MainTitle_Sub[9] = "";
res_helpitem_MainTitle_Sub[10] = " - Border Collapse Setting";
res_helpitem_MainTitle_Sub[11] = " - Border Setting";
res_helpitem_MainTitle_Sub[12] = " - Spacing / Padding Setting";
res_helpitem_MainTitle_Sub[13] = " - Border / Color";
res_helpitem_MainTitle_Sub[14] = " - Border Setting";
res_helpitem_MainTitle_Sub[15] = " - Width / Height / Align";

res_helpitem_MainDescription[0][0] = "Highlight the area and choose fonts in Combo Box. Press the font that you would like to use";
res_helpitem_MainDescription[0][1] = "Highlight the area and choose the size of texts in Combo Box. Press the size that you would like to use.";
res_helpitem_MainDescription[0][2] = "To make your text bold, highlight the area and press Bold. If you want to disable the function press its button again.";
res_helpitem_MainDescription[0][3] = "To make your text italics, highlight the area and press Italics. If you want to disable the function, press its button again.";
res_helpitem_MainDescription[0][4] = "To make your text underlined, highlight the area and press underline. If you want to disable the function,<br />press its button again.";
res_helpitem_MainDescription[0][5] = "To put colors in your text, highlight the area and press color drop down button.<br />Then, choose the color that you would like to change.";
res_helpitem_MainDescription[0][6] = "To put background colors in your text, highlight the area and press background color dropdown button.<br />Then, choose the color that you would like to change.";
res_helpitem_MainDescription[0][7] = "To align your text at the left side of the editing area, highlight the area you want to be aligned and press Left Alignment.";
res_helpitem_MainDescription[0][8] = "To align your text at the center of the editing area, highlight the area you want to be aligned and press Center Alignment.";
res_helpitem_MainDescription[0][9] = "To align your text at the right side of the editing area, highlight the area you want to be aligned and press<br />Right Alignment.";
res_helpitem_MainDescription[0][10] = "To create numbered list, highlight the lines you want to be numbered. Then, the text will automatically gain the number<br />one on the list. If you want to stop Numbered listing, just press again. The function will deactivate.";
res_helpitem_MainDescription[0][11] = "To create bulleted list, highlight the lines you want to be bulleted. Then, the text will automatically gain the bullets<br />on the list. If you want to stop Bulleted listing, just press again. The function will deactivate.";
res_helpitem_MainDescription[0][12] = "To put Letter-Spacing in your text, highlight the area and press Letter-Spacing drop down button.<br />Then, choose the one that you would like to change.";
res_helpitem_MainDescription[0][13] = "To put Line-Height in your text, highlight the area and press Line-Height drop down button.<br />Then, choose the one that you would like to change.";
res_helpitem_MainDescription[0][14] = "To put strike lines on your font, highlight the area and press Strike lines. If you want to disable the function press<br />its button again.";
res_helpitem_MainDescription[0][15] = "Highlight the area you want to put subscript, press Subscript. Then, the text will be placed the bottom of index.<br />If you want to disable the function press its button again.";
res_helpitem_MainDescription[0][16] = "Highlight the area you want to put superscript, press Superscript. Then, the text will be placed the top of index.<br />If you want to disable the function press its button again.";
res_helpitem_MainDescription[0][17] = "Highlight the area and press Increase indentation button. The very front of text line will have no space.";
res_helpitem_MainDescription[0][18] = "Highlight the area and press Decrease indentation button. The front of text line will have space.";

res_helpitem_MainDescription[1][0] = "If you press Create table Dropdown button, selecting row X column will appear.<br />Then place the mouse on rows and columns, and set your own table.";
res_helpitem_MainDescription[1][1] = "If you highlight single row, cell or some rows, inserting row button will activated.<br />Pressing the Insert row button will insert the number of row as much as before the highlighted row.";
res_helpitem_MainDescription[1][2] = "If you highlight some or single row, deleting row button will activated.<br />Pressing the delete row button will delete highlighted area.";
res_helpitem_MainDescription[1][3] = "If you highlight single column, cell or some columns, inserting column button will activated.Pressing the Insert<br />column button will insert the insert the number of columns as much as before the highlighted columns.";
res_helpitem_MainDescription[1][4] = "If you highlight some or single column, deleting column button will be activated.<br />Pressing the delete column button will delete highlighted area.";
res_helpitem_MainDescription[1][5] = "If you highlight number of cells, merging cell button will be activated.<br />Pressing the merge cell button will merge highlighted area.";
res_helpitem_MainDescription[1][6] = "If split cell is on normal state, then split cell button will be activated in highlighted table.<br />Pressing split cell button will split highlighted area.";
res_helpitem_MainDescription[1][7] = "If split column is on normal state, then split column button will be activated in highlighted table.<br />Pressing split column button will split highlighted area.";
res_helpitem_MainDescription[1][8] = "Select the table template you want to create. It will format on each style of table.";
res_helpitem_MainDescription[1][9] = "In order to change the table properties, highlight the part of cells, and press Table Property.<br />Then, Popup window will appear. Set the table using setting properties or preview.";
res_helpitem_MainDescription[1][10] = "Sets adding up borders and cells at the same time.";
res_helpitem_MainDescription[1][11] = "Sets each table border shape, spacing, size, color, and alignment(Left, Top, Right, Bottom)";
res_helpitem_MainDescription[1][12] = "It specifies how thick the cells border will be and sets the height of the cell which demonstrates various forms.";
res_helpitem_MainDescription[1][13] = "In order to change the table properties, highlight the part of cells, and press Cell Property.<br />Then, Popup window will appear. Set the table using setting properties or preview.";
res_helpitem_MainDescription[1][14] = "Apply border shape, size, and color on selected cells.";
res_helpitem_MainDescription[1][15] = "In order to change the cell properties, highlight the part of cells, and press Cell Property.<br />Then, Popup window will appear. On the right top, pressing size/array button, you can set size and layout.";

res_helpitem_MainDescription[2][0] = "Firstly highlight the fragment you want to cut.<br />Go to menu, Edit -> Cut, pressing the combination of Ctrl+X on key board or using popup window menu.";
res_helpitem_MainDescription[2][1] = "Highlight the fragment you want to copy.<br />Go to menu, Edit -> Copy, pressing the combination of Ctrl+C on key board or using popup window menu.";
res_helpitem_MainDescription[2][2] = "Highlight the fragment you want to paste.<br />Go to menu, Edit -> Paste, pressing the combination of Ctrl+V on key board or using popup window menu.";
res_helpitem_MainDescription[2][3] = "Highlight the fragment you want to delete.<br />Go to menu, Edit -> Delete, pressing the Delete on the keyboard or using popup window menu.";
res_helpitem_MainDescription[2][4] = "To highlight all your text, Go to menu, Edit -> Select All, pressing the Ctrl+A on the keyboard";

res_helpitem_MainDescription[3][0] = "Highlight the area you want to Hyper Link, and press Connect Hyperlink button.<br />Set the target of your link when hyperlink properties pop up window appears.<br /> => URL (essential input) : specifies the address you want your link to refer to.<br /> => Target (optional input) : Parent window, New window, Top-most window, Current window<br /> => Tooltip (optional input) : If you move cursor on connected link, tooltip (balloon) will appear.";
res_helpitem_MainDescription[3][1] = "If you select part or whole hyperlink area, remove button will be activated.<br />Pressing remove button will remove the link";
res_helpitem_MainDescription[3][2] = "Select the area to put image file (jpg, gif, png) and press Image insert/property button.<br />Image will upload and appear on your document.";
res_helpitem_MainDescription[3][3] = "Select the Image and press the Insert/properties button. A popup window called Image Property will appear.<br />In this pop up window, you can set image width, height, border.<br /> => URL (essential input) : specifies the address you want your link to refer to.<br /> => Tooltip (optional input) : If you move cursor on connected link, tooltip (balloon) will appear<br /> => Width, Heigth, Border (optional input)";
res_helpitem_MainDescription[3][4] = "Select the area to put Flash file(swf) and press Flash insert/property button.<br />Flash will upload and appear on your document.";
res_helpitem_MainDescription[3][5] = "Select the Flash and press Flash Insert/property button. A popup window called Flash Property will appear.<br />In this pop up window, you can set flash width, height, border.<br /> => URL (essential input) : Flash link address.<br /> => Width, Height (optional input)<br /> => Align (optional input) : specifies the alignment of the Flash. You can choose from: Left, Bottom, Middle, Right.<br /> => Vertical/Horizontal spacing : sets horizontal/vertical spacing.";
res_helpitem_MainDescription[3][6] = "Select the area to put Movie file (wmv) and press movie insert/property button.<br />Movie will upload and appear on your document.<br />(Select the movie and press movie insert/properties then pop up window will appear.)";
res_helpitem_MainDescription[3][7] = "Select the movie and press movie Insert/property button. A popup window called movie Property will appear.<br />In this pop up window, you can set movie width, height, and player property.";
res_helpitem_MainDescription[3][8] = "Select the area to put Special-Character and press Special-Character drop down button.<br />Then, choose the one or more that you would like to insert.";
res_helpitem_MainDescription[3][9] = "To put document background-color, press document background-color drop down button.<br />Then, set background color.";
res_helpitem_MainDescription[3][10] = "To put document background-image, press document background-image button.<br />Image will upload and appear on your document.";
res_helpitem_MainDescription[3][11] = "To put document templete, press document templete button. document templete will appear on your document.";

res_helpitem_MainDescription[4][0] = "Go to Help Menu -> Help. A pop up window will appear called Innoditor users guide";
res_helpitem_MainDescription[4][1] = "Go to Help Menu -> Information. You can check Innoditor information with update date.";

res_helpitem_SubDescription_1[0] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='100' align='center' class='outline'><b>Width/Height</b></td><td width='220' align='center' class='outline'>Set Table Width / Height</td></tr><tr><td align='center' class='outline'><b>Layout</b></td><td align='center' class='outline'>Set Table Layout</td></tr><tr><td align='center' class='outline'><b>Border-Collapse</b></td><td align='center' class='outline'>See Table property detail(1)</td></tr><tr><td align='center' class='outline'><b>Border</b></td><td align='center' class='outline'>See Table property detail(2)</td></tr><tr><td align='center' class='outline'><b>Background</b></td><td align='center' class='outline'>Set Table Background Color</td></tr><tr><td align='center' class='outline'><b>Highlight...</b></td><td align='center' class='outline'>See Table property detail(3)</td></tr><tr><td align='center' class='outline'><b>Cell Padding /<br />Spacing</b></td><td align='center' class='outline'>See Table property detail(4)</td></tr><tr><td align='center' class='outline'><b>Preview</b></td><td align='center' class='outline'>Show changed Table Property<br />Before Apply</td></tr></table>";
res_helpitem_SubDescription_1[1] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='80' align='center' class='outline'><b>Border-<br />Collapse</b></td><td width='560' align='center' class='outline'>Apply : Table Border, Cell Border<br /><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td colspan='2' align='center' class='outline'>Cell Spacing : 0</td><td colspan='2' align='center' class='outline'>Cell Spacing : 1</td><td colspan='2' align='center' class='outline'>Cell Spacing : 4</td></tr><tr><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_1.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_2.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_3.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_4.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_5.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_6.gif' alt='' /></td></tr><tr><td align='center' class='outline'>Yes</td><td align='center' class='outline'>No</td><td align='center' class='outline'>Yes</td><td align='center' class='outline'>No</td><td align='center' class='outline'>Yes</td><td align='center' class='outline'>No</td></tr></table></td></tr><tr><td align='center' class='outline'><b>Cell<br />Apply</b></td><td align='center' class='outline'>Apply : Table Border, Cell Border<br /><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td colspan='2' align='center' class='outline'>Cell Spacing : 0</td><td colspan='2' align='center' class='outline'>Cell Spacing : 1</td><td colspan='2' align='center' class='outline'>Cell Spacing : 4</td></tr><tr><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_7.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_8.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_9.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_10.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_11.gif' alt='' /></td><td width='84' align='center' class='outline'><img src='./image/help_main_1_10_sub_12.gif' alt='' /></td></tr><tr><td align='center' class='outline'>Yes</td><td align='center' class='outline'>No</td><td align='center' class='outline'>Yes</td><td align='center' class='outline'>No</td><td align='center' class='outline'>Yes</td><td align='center' class='outline'>No</td></tr></table></td></tr></table>";
res_helpitem_SubDescription_1[2] = "<table border='0' cellpadding='0' cellspacing='0' width='100%'><tr><td colspan='4' height='3'></td></tr><tr><td width='10'></td><td align='center'><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='80' align='center' class='outline'><b>Each<br />Apply</b></td><td width='560' align='center' class='outline'>Set Table Border - Left, Top, Right, Bottom</td></tr><tr><td align='center' class='outline'><b>Style/Width</b></td><td align='center' class='outline'>Set Table Border Style, Width<br />double or 3D must 3px over<br /><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_1.gif' alt='' /></td><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_2.gif' alt='' /></td><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_3.gif' alt='' /></td><td width='120' align='center' class='outline'><img src='./image/help_main_1_11_sub_4.gif' alt='' /></td></tr><tr><td align='center' class='outline'>solid / 1px</td><td align='center' class='outline'>dotted / 1px</td><td align='center' class='outline'>dashed / 1px</td><td align='center' class='outline'>double / 4px</td></tr><tr><td align='center' class='outline'><img src='./image/help_main_1_11_sub_5.gif' alt='' /></td><td align='center' class='outline'><img src='./image/help_main_1_11_sub_6.gif' alt='' /></td><td align='center' class='outline'><img src='./image/help_main_1_11_sub_7.gif' alt='' /></td><td align='center' class='outline'><img src='./image/help_main_1_11_sub_8.gif' alt='' /></td></tr><tr><td align='center' class='outline'>groove(3D) / 4px</td><td align='center' class='outline'>ridge(3D) / 4px</td><td align='center' class='outline'>inset(3D) / 4px</td><td align='center' class='outline'>outset(3D) / 4px</td></tr></table></td></tr><tr><td width='80' align='center' class='outline'><b>Border Color</b></td><td width='560' align='center' class='outline'>Set Table Border Color</td></tr></table></td><td width='10'></td></tr><tr><td colspan='4' height='3'></td></tr></table>";
res_helpitem_SubDescription_1[3] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='80' align='center' class='outline'><b>Cell Spacing</b></td><td width='560' align='center' class='outline'><table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_1.gif' alt='' /></td><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_2.gif' alt='' /></td><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_3.gif' alt='' /></td><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_4.gif' alt='' /></td><td width='100' align='center' class='outline'><img src='./image/help_main_1_12_sub_5.gif' alt='' /></td></tr><tr><td align='center' class='outline'>Spacing : 0<br />Border-Collapse : Y<br />Border Width : 1</td><td align='center' class='outline'>Spacing : 2<br />Border-Collapse : Y<br />Border Width : 1</td><td align='center' class='outline'>Spacing : 2<br />Border-Collapse : N<br />Border Width : 1</td><td align='center' class='outline'>Spacing : 6<br />Border-Collapse : Y<br />Border Width : 1</td><td align='center' class='outline'>Spacing : 6<br />Border-Collapse : N<br />Border Width : 0</td></tr></table></td></tr><tr><td align='center' class='outline'><b>Cell Padding</b></td><td align='center' class='outline'>Set Cell Padding</td></tr></table>";
res_helpitem_SubDescription_1[4] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='100' align='center' class='outline'><b>Select cell</b></td><td width='220' align='center' class='outline'>This shows cell property before<br />Cell properties pop up window.<br />If you click the selected cell,<br />it will be selected or unselected<br />and the other cells can be selected<br />in same way.<br />It provides preview before modifying<br />the cell property just like<br />table preview.<br /></td></tr><tr><td align='center' class='outline'><b>Setting<br />Cell Border</b></td><td align='center' class='outline'>Setting borders of size, style,<br />color and background color in each<br />cells, may caused by table property.<br />If this happens, you may remove table<br />property, and set cell properties.<br />(Add borders-remove, size-0, color-remove<br />are the same as Table Property)</td></tr><tr><td align='center' class='outline'><b>Cell<br />background color</b></td><td align='center' class='outline'>Press the right color button,<br />and choose the color you want to use.<br />If background color cell is<br />not settled, then table background<br />will be colored.</td></tr><tr><td align='center' class='outline'><b>Apply cell border</b></td><td align='center' class='outline'>See Cell property detail(1)</td></tr></table>";
res_helpitem_SubDescription_1[5] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='90' align='center' class='outline'><b>Style</b></td><td width='220' align='center' class='outline'>Sets cells border style.<br />(Same as Table border style.<br />See Table property detail(2))<br /></td></tr><tr><td align='center' class='outline'><b>Width/Height</b></td><td align='center' class='outline'>Sets cells border width/height.<br />(Same as Table border width/height.<br />See Table property detail(2))<br /></td></tr><tr><td align='center' class='outline'><b>Color</b></td><td align='center' class='outline'>Select cell border color<br /></td></tr><tr><td align='center' class='outline'><b>Select Border</b></td><td align='center' class='outline'>After selecting border style,size,color,<br />select right, left, top, bottom<br />using cursor.</td></tr></table>";
res_helpitem_SubDescription_1[6] = "<b>Cell Border Example</b>";
res_helpitem_SubDescription_1[7] = "<table cellspacing='0' cellpadding='0' style='border-collapse:collapse'><tr><td width='90' align='center' class='outline'><b>Select cell</b></td><td width='220' align='center' class='outline'>This shows cell property before<br />Cell properties pop up window.<br />If you click the selected cell,<br />it will be selected or unselected<br />and the other cells can be selected<br />in same way.</td></tr><tr><td align='center' class='outline'><b>Width/Height</b></td><td align='center' class='outline'>Set the selected cells width/height.<br />If it is not settled, you may not set<br />cell size. However, you may<br />set width or height separately.</td></tr><tr><td align='center' class='outline'><b>Layout</b></td><td align='center' class='outline'>Layout selected horizontal and<br />vertical alignment.<br />(Horizontal – left, center, right<br />Vertical- top, center, bottom.)</td></tr></table>";
