package wt.part;

import wt.util.WTException;

import com.ptc.windchill.annotations.metadata.GenAsObjectMappable;
import com.ptc.windchill.annotations.metadata.GeneratedProperty;
import com.ptc.windchill.annotations.metadata.PropertyConstraints;
import com.ptc.windchill.annotations.metadata.Serialization;

/**
 * This is the 'Standard Soft Attribute' cookie class implementation for the corresponding cookie class interface.<br>
 * This implementation can be updated to include additional storage columns for 'Standard Soft Attributes' by running the AddColumns tool.<br>
 * (See Windchill Customizer's Guide for more details.)<br>
 * <br>
 * <br>
 * This standard attribute cookie has 120 String, 0 Long, 0 Double, 0 Boolean, 0 Timestamp, 0 ObjectReference, 0 VersionReference, 0
 * InlineBLOB columns.
 * 
 */
@GenAsObjectMappable(serializable = Serialization.EXTERNALIZABLE_BASIC, properties = {
        @GeneratedProperty(name = "ptc_str_1", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_2", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_3", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_4", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_5", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_6", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_7", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_8", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_9", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_10", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_11", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_12", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_13", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_14", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_15", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_16", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_17", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_18", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_19", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_20", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_21", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_22", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_23", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_24", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_25", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_26", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_27", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_28", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_29", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_30", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_31", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_32", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_33", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_34", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_35", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_36", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_37", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_38", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_39", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_40", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_41", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_42", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_43", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_44", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_45", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_46", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_47", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_48", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_49", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_50", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_51", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_52", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_53", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_54", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_55", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_56", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_57", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_58", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_59", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_60", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_61", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_62", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_63", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_64", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_65", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_66", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_67", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_68", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_69", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_70", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_71", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_72", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_73", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_74", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_75", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_76", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_77", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_78", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_79", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_80", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_81", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_82", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_83", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_84", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_85", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_86", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_87", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_88", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_89", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_90", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_91", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_92", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_93", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_94", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_95", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_96", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_97", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_98", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_99", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_100", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_101", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_102", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_103", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_104", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_105", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_106", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_107", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_108", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_109", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_110", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_111", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_112", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_113", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_114", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_115", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_116", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_117", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_118", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_119", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_120", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_121", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_122", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_123", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_124", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_125", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_126", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_127", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_128", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_129", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_130", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_131", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_132", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_133", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_134", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_135", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_136", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_137", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_138", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_139", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_140", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_141", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_142", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_143", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_144", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_145", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_146", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_147", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_148", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_149", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_150", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_151", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_152", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_153", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_154", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_155", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_156", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_157", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_158", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_159", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_160", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_161", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_162", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_163", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_164", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_165", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_166", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_167", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_168", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_169", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_170", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_171", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_172", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_173", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_174", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_175", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_176", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_177", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_178", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_179", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_180", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_181", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_182", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)),
        @GeneratedProperty(name = "ptc_str_183", type = String.class, constraints = @PropertyConstraints(upperLimit = 1500)) })
public class WTPartTypeInfo extends _WTPartTypeInfo {
    static final long serialVersionUID = 1;

    public static WTPartTypeInfo newWTPartTypeInfo() throws WTException {
	WTPartTypeInfo instance = new WTPartTypeInfo();
	instance.initialize();
	return instance;
    }

    protected void initialize() throws WTException {
    }
}
