-- 자동차 일정 OEMPLAN - OEMENDDATE
CREATE OR REPLACE FUNCTION FN_GET_OEMPLAN_OEMENDDATE(V_MPOID    IN VARCHAR2
                                                    ,V_VIEWTYPE IN VARCHAR2)
RETURN  VARCHAR2
IS
    V_RETURN VARCHAR2(200);
   
BEGIN
    SELECT TO_CHAR(OEMENDDATE,'YY/MM/DD') INTO V_RETURN
      FROM OEMPLAN
     WHERE IDA3B3 = V_MPOID
       AND VIEWTYPE = V_VIEWTYPE;
     
     RETURN V_RETURN;
END;

CREATE OR REPLACE FUNCTION FN_GET_OEMPLAN_OEMENDDATE_SOP(V_MPOID IN VARCHAR2)
RETURN  VARCHAR2
IS
    V_RETURN VARCHAR2(200);
   
BEGIN
    SELECT TO_CHAR(OP.OEMENDDATE,'YY/MM/DD') INTO V_RETURN
      FROM OEMPLAN        OP
          ,OEMPROJECTTYPE OEM
     WHERE OP.IDA3A3 = OEM.IDA2A2(+)
       AND OEM.NAME = 'SOP'
       AND IDA3B3 = V_MPOID;
     
     RETURN V_RETURN;
END;