[
    {
        "rev": "0.0",
        "econo": "-",
        "partNo": "H641071",
        "partName": "임시",
        "ict": "-",
        "children": [
            {
                "rev": "0.0",
                "econo": "-",
                "partNo": "H671069",
                "partName": "090II 15M HOUSING",
                "ict": "-",
                "parentNo": "H641071",
                "children": [
                    {
                        "rev": "0.0",
                        "econo": "-",
                        "partNo": "R200071",
                        "partName": "PBT- GP1000H NP",
                        "ict": "-",
                        "parentNo": "H671069",
                        "children": [],
                        "qty": "10.695",
                        "leaf": true,
                        "iconCls": "task",
                        "bom_path": "1^H641071|2^H671069|",
                        "unit": "KET_G",
                        "lvl": "2",
                        "seq": "20",
                        "pver": "0.0",
                        "checkout": "테스트"
                    },
                    {
                        "rev": "0.0",
                        "econo": "-",
                        "partNo": "S200071",
                        "partName": "SCRAP-GP1000H NP",
                        "ict": "-",
                        "parentNo": "H671069",
                        "children": [],
                        "qty": "-1.173",
                        "leaf": true,
                        "iconCls": "task",
                        "bom_path": "1^H641071|2^H671069|",
                        "unit": "KET_G",
                        "lvl": "2",
                        "seq": "10",
                        "pver": "0.0",
                        "checkout": "테스트"
                    }
                ],
                "qty": "1.000",
                "leaf": false,
                "iconCls": "task-folder",
                "bom_path": "1^H641071|",
                "unit": "KET_EA",
                "lvl": "1",
                "seq": "10",
                "pver": "0.0",
                "checkout": "테스트"
            },
            {
                "rev": "0.0",
                "econo": "-",
                "partNo": "H671070",
                "partName": "090II 15M SPACER",
                "ict": "-",
                "parentNo": "H641071",
                "children": [
                    {
                        "rev": "0.0",
                        "econo": "-",
                        "partNo": "R200082",
                        "partName": "PBT- GP1000S NP",
                        "ict": "-",
                        "parentNo": "H671070",
                        "children": [],
                        "qty": "1.348",
                        "leaf": true,
                        "iconCls": "task",
                        "bom_path": "1^H641071|2^H671070|",
                        "unit": "KET_G",
                        "lvl": "2",
                        "seq": "10",
                        "pver": "0.0",
                        "checkout": "테스트"
                    },
                    {
                        "rev": "0.0",
                        "econo": "-",
                        "partNo": "S200082",
                        "partName": "SCRAP-GP1000S NP",
                        "ict": "-",
                        "parentNo": "H671070",
                        "children": [],
                        "qty": "-.539",
                        "leaf": true,
                        "iconCls": "task",
                        "bom_path": "1^H641071|2^H671070|",
                        "unit": "KET_G",
                        "lvl": "2",
                        "seq": "20",
                        "pver": "0.0",
                        "checkout": "테스트"
                    }
                ],
                "qty": "1.000",
                "leaf": false,
                "iconCls": "task-folder",
                "bom_path": "1^H641071|",
                "unit": "KET_EA",
                "lvl": "1",
                "seq": "20",
                "pver": "0.0",
                "checkout": "테스트"
            }
        ],
        "parentNo": "",
        "qty": "-",
        "leaf": false,
        "iconCls": "task-folder",
        "bom_path": "",
        "unit": "-",
        "lvl": "0",
        "seq": "-",
        "pver": "",
        "checkout": "checkout"
    }
]