package ext.ket.edm.service;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.List;
import java.util.Map;

import e3ps.common.util.StringUtil;

public class PlmHpIfSendDao {

	private Connection conn;

	public PlmHpIfSendDao(Connection conn) {
		this.conn = conn;
	}

	public PlmHpIfSendDao() {
		super();
	}

	/**
	 * 함수명 : SearchRepass 설명 : 개발담당자 결재
	 * 
	 * @param
	 * @return ArrayList
	 * @throws Exception
	 * @throws 작성자
	 *             : 황정태 작성일자 : 2012. 07. 02.
	 */
	public int savePlmHpIf(List<Map<String, Object>> distReqEpmDocList) throws Exception {
		PreparedStatement pstmt = null;
		int complet = 0;
		try {
			StringBuilder sb = new StringBuilder();

			for (Map<String, Object> sendList : distReqEpmDocList) {
				sb.append(" MERGE KETPLM.dbo.WKET_IF001 A \n");
				sb.append(" USING (SELECT '" + StringUtil.checkNull(sendList.get("sPartNumberDrawingNumber").toString()).trim() + "' AS PartNumber) AS B");
				sb.append(" ON (A.PartNumber = B.PartNumber) \n");
				sb.append(" WHEN MATCHED THEN \n");
				sb.append(" UPDATE SET \n ");
				sb.append("\n 	spCategoryCode=?,spClassification=?,PartName=?,PartNumber=?,spDivision=?,spProjectNo=?,spEoNo=?,spPartStyle=?,spPartNameHis=?,spPartRevision=?,");
				sb.append("\n 	spPartType=?,spPartDevLevel=?,spIsDeleted=?,spBOMFlag=?,spWeightUnit=?,spNetWeight=?,spTotalWeight=?,spScrabWeight=?,spIsYazaki=?,");
				sb.append("\n 	spYazakiNo=?,spManufAt=?,spManufacPlace=?,spCustomRev=?,spScrabCode=?,spWaterProof=?,spMaterialMark=?,spColor=?,spColorPurch=?,");
				sb.append("\n 	spColorElec=?,spSeries=?,spSeriesLAMP=?,spSeriesBulb=?,spProdSize=?,spEnvFriend=?,spTGenConn=?,spTPCBConn=?,spTLAMPConn=?,spTBulbConn=?,");
				sb.append("\n 	spTHiVolt=?,spTCharger=?,spT2Charger=?,spT1HiVoltFuz=?,spTHiVoltFuse=?,spTJnB=?,spTPRA=?,spTGNSS=?,spTComModule=?,spTMultiMedUnit=?,");
				sb.append("\n 	spLanceType=?,spNoOfPole=?,spMTerminal=?,spMConnector=?,spMatchBulb=?,spMClip=?,spMRH=?,spMCover=?,spLockingType=?,spLockTTML=?,");
				sb.append("\n 	spLockTConn=?,spMWireSeal=?,spRepresentM=?,spMaterMaker=?,spMaterType=?,spMaterialInfo=?,spMaterNotFe=?,spMaterDie=?,spMaterPurch=?,");
				sb.append("\n 	spPlating=?,spPlatingPurch=?,spCustomPartNo=?,spPermitVolt=?,spWireRangeAWG=?,spWireRAWGElec=?,spWireRangeMm=?,spTabThickness=?,");
				sb.append("\n 	spMaterThick=?,spBracketSizeD=?,spBracketSizeH=?,spBracketSizeT=?,spRelayCapa=?,spEResistVal=?,spVoltSensCapa=?,spManufPartNo=?,");
				sb.append("\n 	spValueValue=?,spTolerance=?,spManufacturer=?,spRatedVoltage=?,spWatt=?,spOperTemp=?,spStoreTemp=?,spPackageType=?,spMSL=?,spESD=?,");
				sb.append("\n 	spAECQ=?,spCharact1=?,spCharact2=?,spHoleSize=?,spWireRangeSQ=?,spWATTW=?,spSizemm=?,spPermitTempC=?,spIsResin=?,spThickness=?,spHoleShape=?,");
				sb.append("\n 	spCapaEResist=?,spClothesMater=?,spIsShield=?,spESIRApproval=?,spISIRApproval=?,spConAppNoESIR=?,spLayer=?,spOrgDskPartNo=?,spPCBMaterial=?,");
				sb.append("\n 	spTg=?,spCharact=?,spSurfaceTreat=?,spAppearanProc=?,spSoldResColor=?,spInstallPos=?,spSwVersion=?,spUnitUnit=?,spResUnit=?,spINDUnit=?,");
				sb.append("\n 	spCapUnit=?,spRLCPackType=?,spRLCTolerance=?,spFestPrevent=?,spConnCombDir=?,spCertified=?,spPackageSpec=?,spTabSize=?,spSealType=?,");
				sb.append("\n 	spStudSize=?,spPitch=?,spSoldering=?,spConstrucMeth=?,spOptimumTemp=?,spContactRes=?,spInsulatRes=?,spConntHeight=?,spCableConMeth=?,");
				sb.append("\n 	spTerminalType=?,spTermBarrelSz=?,spTermPrezType=?,spGWITMaterAt=?,spInterface=?,spPinNShape=?,spSUBSuppliy=?,spCodingNColor=?,");
				sb.append("\n 	spPlant=?,spPuchaseGroup=?,spDevManNm=?,spDesignManNm=?,spManufacManNm=?,spMContractSAt=?,spMMoldAt=?,spMMakingAt=?,spMProdAt=?,");
				sb.append("\n 	spDieWhere=?,spObjectiveCT=?,spCavityStd=?,spMountWayApE=?,spThickWH=?,spPropEtc=?,spHighVoltageSensingLimit=?,spMovVoltage=?,");
				sb.append("\n 	spToleranceSensing=?,spEsirApprove=?,spMainChipset=?,spFrequency=?,spDcpower=?,spInterfaceIt=?,spFeatures=?,spDevSpec=?,");
				sb.append("\n 	spFlameLevel=?,spERatedVoltage=?,spQCNo=?,spActuatorLctn=?,spMaxFrequency=?,spImpedance=?,spAssemblyMaterial=?,spDescription=?,");
				sb.append("\n 	spImgFile=?,sp2DpdfFile=?,sp3DpdfFile=?,spStepFile=?,spIgsFile=?,spInstructionsFile=?,USE_YN=?,spMasterName=?,spMasterEmail=?, RGST_DTM=GETDATE()");
				sb.append(" WHEN NOT MATCHED THEN \n");
				sb.append(" INSERT ");
				sb.append("\n (	spCategoryCode,spClassification,PartName,PartNumber,spDivision,spProjectNo,spEoNo,spPartStyle,spPartNameHis,spPartRevision,");
				sb.append("\n 	spPartType,spPartDevLevel,spIsDeleted,spBOMFlag,spWeightUnit,spNetWeight,spTotalWeight,spScrabWeight,spIsYazaki,");
				sb.append("\n 	spYazakiNo,spManufAt,spManufacPlace,spCustomRev,spScrabCode,spWaterProof,spMaterialMark,spColor,spColorPurch,");
				sb.append("\n 	spColorElec,spSeries,spSeriesLAMP,spSeriesBulb,spProdSize,spEnvFriend,spTGenConn,spTPCBConn,spTLAMPConn,spTBulbConn,");
				sb.append("\n 	spTHiVolt,spTCharger,spT2Charger,spT1HiVoltFuz,spTHiVoltFuse,spTJnB,spTPRA,spTGNSS,spTComModule,spTMultiMedUnit,");
				sb.append("\n 	spLanceType,spNoOfPole,spMTerminal,spMConnector,spMatchBulb,spMClip,spMRH,spMCover,spLockingType,spLockTTML,");
				sb.append("\n 	spLockTConn,spMWireSeal,spRepresentM,spMaterMaker,spMaterType,spMaterialInfo,spMaterNotFe,spMaterDie,spMaterPurch,");
				sb.append("\n 	spPlating,spPlatingPurch,spCustomPartNo,spPermitVolt,spWireRangeAWG,spWireRAWGElec,spWireRangeMm,spTabThickness,");
				sb.append("\n 	spMaterThick,spBracketSizeD,spBracketSizeH,spBracketSizeT,spRelayCapa,spEResistVal,spVoltSensCapa,spManufPartNo,");
				sb.append("\n 	spValueValue,spTolerance,spManufacturer,spRatedVoltage,spWatt,spOperTemp,spStoreTemp,spPackageType,spMSL,spESD,");
				sb.append("\n 	spAECQ,spCharact1,spCharact2,spHoleSize,spWireRangeSQ,spWATTW,spSizemm,spPermitTempC,spIsResin,spThickness,spHoleShape,");
				sb.append("\n 	spCapaEResist,spClothesMater,spIsShield,spESIRApproval,spISIRApproval,spConAppNoESIR,spLayer,spOrgDskPartNo,spPCBMaterial,");
				sb.append("\n 	spTg,spCharact,spSurfaceTreat,spAppearanProc,spSoldResColor,spInstallPos,spSwVersion,spUnitUnit,spResUnit,spINDUnit,");
				sb.append("\n 	spCapUnit,spRLCPackType,spRLCTolerance,spFestPrevent,spConnCombDir,spCertified,spPackageSpec,spTabSize,spSealType,");
				sb.append("\n 	spStudSize,spPitch,spSoldering,spConstrucMeth,spOptimumTemp,spContactRes,spInsulatRes,spConntHeight,spCableConMeth,");
				sb.append("\n 	spTerminalType,spTermBarrelSz,spTermPrezType,spGWITMaterAt,spInterface,spPinNShape,spSUBSuppliy,spCodingNColor,");
				sb.append("\n 	spPlant,spPuchaseGroup,spDevManNm,spDesignManNm,spManufacManNm,spMContractSAt,spMMoldAt,spMMakingAt,spMProdAt,");
				sb.append("\n 	spDieWhere,spObjectiveCT,spCavityStd,spMountWayApE,spThickWH,spPropEtc,spHighVoltageSensingLimit,spMovVoltage,");
				sb.append("\n 	spToleranceSensing,spEsirApprove,spMainChipset,spFrequency,spDcpower,spInterfaceIt,spFeatures,spDevSpec,");
				sb.append("\n 	spFlameLevel,spERatedVoltage,spQCNo,spActuatorLctn,spMaxFrequency,spImpedance,spAssemblyMaterial,spDescription,");
				sb.append("\n 	spImgFile,sp2DpdfFile,sp3DpdfFile,spStepFile,spIgsFile,spInstructionsFile,USE_YN,spMasterName,spMasterEmail, RGST_DTM");
				sb.append("\n )");
				sb.append("\n VALUES");
				sb.append("\n (");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, GETDATE() );");

				pstmt = conn.prepareStatement(sb.toString());
				// sb.append("'").append(sendList.get("sPartNumberDrawingNumber")).append("',");
				// sb.append("'").append(sendList.get("PartNumber")).append("',");

				pstmt.setString(1, StringUtil.checkNull(sendList.get("spCategoryCode").toString()).trim());
				pstmt.setString(2, StringUtil.checkNull(sendList.get("spClassification").toString()).trim());
				pstmt.setString(3, StringUtil.checkNull(sendList.get("PartName").toString()).trim());
				pstmt.setString(4, StringUtil.checkNull(sendList.get("sPartNumberDrawingNumber").toString()).trim());
				pstmt.setString(5, StringUtil.checkNull(sendList.get("spDivision").toString()).trim());
				pstmt.setString(6, StringUtil.checkNull(sendList.get("spProjectNo").toString()).trim());
				pstmt.setString(7, StringUtil.checkNull(sendList.get("spEoNo").toString()).trim());
				pstmt.setString(8, StringUtil.checkNull(sendList.get("spPartStyle").toString()).trim());
				pstmt.setString(9, StringUtil.checkNull(sendList.get("spPartNameHis").toString()).trim());
				pstmt.setString(10, StringUtil.checkNull(sendList.get("spPartRevision").toString()).trim());
				pstmt.setString(11, StringUtil.checkNull(sendList.get("spPartType").toString()).trim());
				pstmt.setString(12, StringUtil.checkNull(sendList.get("spPartDevLevel").toString()).trim());
				pstmt.setString(13, StringUtil.checkNull(sendList.get("spIsDeleted").toString()).trim());
				pstmt.setString(14, StringUtil.checkNull(sendList.get("spBOMFlag").toString()).trim());
				pstmt.setString(15, StringUtil.checkNull(sendList.get("spWeightUnit").toString()).trim());
				pstmt.setString(16, StringUtil.checkNull(sendList.get("spNetWeight").toString()).trim());
				pstmt.setString(17, StringUtil.checkNull(sendList.get("spTotalWeight").toString()).trim());
				pstmt.setString(18, StringUtil.checkNull(sendList.get("spScrabWeight").toString()).trim());
				pstmt.setString(19, StringUtil.checkNull(sendList.get("spIsYazaki").toString()).trim());
				pstmt.setString(20, StringUtil.checkNull(sendList.get("spYazakiNo").toString()).trim());
				pstmt.setString(21, StringUtil.checkNull(sendList.get("spManufAt").toString()).trim());
				pstmt.setString(22, StringUtil.checkNull(sendList.get("spManufacPlace").toString()).trim());
				pstmt.setString(23, StringUtil.checkNull(sendList.get("spCustomRev").toString()).trim());
				pstmt.setString(24, StringUtil.checkNull(sendList.get("spScrabCode").toString()).trim());
				pstmt.setString(25, StringUtil.checkNull(sendList.get("spWaterProof").toString()).trim());
				pstmt.setString(26, StringUtil.checkNull(sendList.get("spMaterialMark").toString()).trim());
				pstmt.setString(27, StringUtil.checkNull(sendList.get("spColor").toString()).trim());
				pstmt.setString(28, StringUtil.checkNull(sendList.get("spColorPurch").toString()).trim());
				pstmt.setString(29, StringUtil.checkNull(sendList.get("spColorElec").toString()).trim());
				pstmt.setString(30, StringUtil.checkNull(sendList.get("spSeries").toString()).trim());
				pstmt.setString(31, StringUtil.checkNull(sendList.get("spSeriesLAMP").toString()).trim());
				pstmt.setString(32, StringUtil.checkNull(sendList.get("spSeriesBulb").toString()).trim());
				pstmt.setString(33, StringUtil.checkNull(sendList.get("spProdSize").toString()).trim());
				pstmt.setString(34, StringUtil.checkNull(sendList.get("spEnvFriend").toString()).trim());
				pstmt.setString(35, StringUtil.checkNull(sendList.get("spTGenConn").toString()).trim());
				pstmt.setString(36, StringUtil.checkNull(sendList.get("spTPCBConn").toString()).trim());
				pstmt.setString(37, StringUtil.checkNull(sendList.get("spTLAMPConn").toString()).trim());
				pstmt.setString(38, StringUtil.checkNull(sendList.get("spTBulbConn").toString()).trim());
				pstmt.setString(39, StringUtil.checkNull(sendList.get("spTHiVolt").toString()).trim());
				pstmt.setString(40, StringUtil.checkNull(sendList.get("spTCharger").toString()).trim());
				pstmt.setString(41, StringUtil.checkNull(sendList.get("spT2Charger").toString()).trim());
				pstmt.setString(42, StringUtil.checkNull(sendList.get("spT1HiVoltFuz").toString()).trim());
				pstmt.setString(43, StringUtil.checkNull(sendList.get("spTHiVoltFuse").toString()).trim());
				pstmt.setString(44, StringUtil.checkNull(sendList.get("spTJnB").toString()).trim());
				pstmt.setString(45, StringUtil.checkNull(sendList.get("spTPRA").toString()).trim());
				pstmt.setString(46, StringUtil.checkNull(sendList.get("spTGNSS").toString()).trim());
				pstmt.setString(47, StringUtil.checkNull(sendList.get("spTComModule").toString()).trim());
				pstmt.setString(48, StringUtil.checkNull(sendList.get("spTMultiMedUnit").toString()).trim());
				pstmt.setString(49, StringUtil.checkNull(sendList.get("spLanceType").toString()).trim());
				pstmt.setString(50, StringUtil.checkNull(sendList.get("spNoOfPole").toString()).trim());
				pstmt.setString(51, StringUtil.checkNull(sendList.get("spMTerminal").toString()).trim());
				pstmt.setString(52, StringUtil.checkNull(sendList.get("spMConnector").toString()).trim());
				pstmt.setString(53, StringUtil.checkNull(sendList.get("spMatchBulb").toString()).trim());
				pstmt.setString(54, StringUtil.checkNull(sendList.get("spMClip").toString()).trim());
				pstmt.setString(55, StringUtil.checkNull(sendList.get("spMRH").toString()).trim());
				pstmt.setString(56, StringUtil.checkNull(sendList.get("spMCover").toString()).trim());
				pstmt.setString(57, StringUtil.checkNull(sendList.get("spLockingType").toString()).trim());
				pstmt.setString(58, StringUtil.checkNull(sendList.get("spLockTTML").toString()).trim());
				pstmt.setString(59, StringUtil.checkNull(sendList.get("spLockTConn").toString()).trim());
				pstmt.setString(60, StringUtil.checkNull(sendList.get("spMWireSeal").toString()).trim());
				pstmt.setString(61, StringUtil.checkNull(sendList.get("spRepresentM").toString()).trim());
				pstmt.setString(62, StringUtil.checkNull(sendList.get("spMaterMaker").toString()).trim());
				pstmt.setString(63, StringUtil.checkNull(sendList.get("spMaterType").toString()).trim());
				pstmt.setString(64, StringUtil.checkNull(sendList.get("spMaterialInfo").toString()).trim());
				pstmt.setString(65, StringUtil.checkNull(sendList.get("spMaterNotFe").toString()).trim());
				pstmt.setString(66, StringUtil.checkNull(sendList.get("spMaterDie").toString()).trim());
				pstmt.setString(67, StringUtil.checkNull(sendList.get("spMaterPurch").toString()).trim());
				pstmt.setString(68, StringUtil.checkNull(sendList.get("spPlating").toString()).trim());
				pstmt.setString(69, StringUtil.checkNull(sendList.get("spPlatingPurch").toString()).trim());
				pstmt.setString(70, StringUtil.checkNull(sendList.get("spCustomPartNo").toString()).trim());
				pstmt.setString(71, StringUtil.checkNull(sendList.get("spPermitVolt").toString()).trim());
				pstmt.setString(72, StringUtil.checkNull(sendList.get("spWireRangeAWG").toString()).trim());
				pstmt.setString(73, StringUtil.checkNull(sendList.get("spWireRAWGElec").toString()).trim());
				pstmt.setString(74, StringUtil.checkNull(sendList.get("spWireRangeMm").toString()).trim());
				pstmt.setString(75, StringUtil.checkNull(sendList.get("spTabThickness").toString()).trim());
				pstmt.setString(76, StringUtil.checkNull(sendList.get("spMaterThick").toString()).trim());
				pstmt.setString(77, StringUtil.checkNull(sendList.get("spBracketSizeD").toString()).trim());
				pstmt.setString(78, StringUtil.checkNull(sendList.get("spBracketSizeH").toString()).trim());
				pstmt.setString(79, StringUtil.checkNull(sendList.get("spBracketSizeT").toString()).trim());
				pstmt.setString(80, StringUtil.checkNull(sendList.get("spRelayCapa").toString()).trim());
				pstmt.setString(81, StringUtil.checkNull(sendList.get("spEResistVal").toString()).trim());
				pstmt.setString(82, StringUtil.checkNull(sendList.get("spVoltSensCapa").toString()).trim());
				pstmt.setString(83, StringUtil.checkNull(sendList.get("spManufPartNo").toString()).trim());
				pstmt.setString(84, StringUtil.checkNull(sendList.get("spValueValue").toString()).trim());
				pstmt.setString(85, StringUtil.checkNull(sendList.get("spTolerance").toString()).trim());
				pstmt.setString(86, StringUtil.checkNull(sendList.get("spManufacturer").toString()).trim());
				pstmt.setString(87, StringUtil.checkNull(sendList.get("spRatedVoltage").toString()).trim());
				pstmt.setString(88, StringUtil.checkNull(sendList.get("spWatt").toString()).trim());
				pstmt.setString(89, StringUtil.checkNull(sendList.get("spOperTemp").toString()).trim());
				pstmt.setString(90, StringUtil.checkNull(sendList.get("spStoreTemp").toString()).trim());
				pstmt.setString(91, StringUtil.checkNull(sendList.get("spPackageType").toString()).trim());
				pstmt.setString(92, StringUtil.checkNull(sendList.get("spMSL").toString()).trim());
				pstmt.setString(93, StringUtil.checkNull(sendList.get("spESD").toString()).trim());
				pstmt.setString(94, StringUtil.checkNull(sendList.get("spAECQ").toString()).trim());
				pstmt.setString(95, StringUtil.checkNull(sendList.get("spCharact1").toString()).trim());
				pstmt.setString(96, StringUtil.checkNull(sendList.get("spCharact2").toString()).trim());
				pstmt.setString(97, StringUtil.checkNull(sendList.get("spHoleSize").toString()).trim());
				pstmt.setString(98, StringUtil.checkNull(sendList.get("spWireRangeSQ").toString()).trim());
				pstmt.setString(99, StringUtil.checkNull(sendList.get("spWATTW").toString()).trim());
				pstmt.setString(100, StringUtil.checkNull(sendList.get("spSizemm").toString()).trim());
				pstmt.setString(101, StringUtil.checkNull(sendList.get("spPermitTempC").toString()).trim());
				pstmt.setString(102, StringUtil.checkNull(sendList.get("spIsResin").toString()).trim());
				pstmt.setString(103, StringUtil.checkNull(sendList.get("spThickness").toString()).trim());
				pstmt.setString(104, StringUtil.checkNull(sendList.get("spHoleShape").toString()).trim());
				pstmt.setString(105, StringUtil.checkNull(sendList.get("spCapaEResist").toString()).trim());
				pstmt.setString(106, StringUtil.checkNull(sendList.get("spClothesMater").toString()).trim());
				pstmt.setString(107, StringUtil.checkNull(sendList.get("spIsShield").toString()).trim());
				pstmt.setString(108, StringUtil.checkNull(sendList.get("spESIRApproval").toString()).trim());
				pstmt.setString(109, StringUtil.checkNull(sendList.get("spISIRApproval").toString()).trim());
				pstmt.setString(110, StringUtil.checkNull(sendList.get("spConAppNoESIR").toString()).trim());
				pstmt.setString(111, StringUtil.checkNull(sendList.get("spLayer").toString()).trim());
				pstmt.setString(112, StringUtil.checkNull(sendList.get("spOrgDskPartNo").toString()).trim());
				pstmt.setString(113, StringUtil.checkNull(sendList.get("spPCBMaterial").toString()).trim());
				pstmt.setString(114, StringUtil.checkNull(sendList.get("spTg").toString()).trim());
				pstmt.setString(115, StringUtil.checkNull(sendList.get("spCharact").toString()).trim());
				pstmt.setString(116, StringUtil.checkNull(sendList.get("spSurfaceTreat").toString()).trim());
				pstmt.setString(117, StringUtil.checkNull(sendList.get("spAppearanProc").toString()).trim());
				pstmt.setString(118, StringUtil.checkNull(sendList.get("spSoldResColor").toString()).trim());
				pstmt.setString(119, StringUtil.checkNull(sendList.get("spInstallPos").toString()).trim());
				pstmt.setString(120, StringUtil.checkNull(sendList.get("spSwVersion").toString()).trim());
				pstmt.setString(121, StringUtil.checkNull(sendList.get("spUnitUnit").toString()).trim());
				pstmt.setString(122, StringUtil.checkNull(sendList.get("spResUnit").toString()).trim());
				pstmt.setString(123, StringUtil.checkNull(sendList.get("spINDUnit").toString()).trim());
				pstmt.setString(124, StringUtil.checkNull(sendList.get("spCapUnit").toString()).trim());
				pstmt.setString(125, StringUtil.checkNull(sendList.get("spRLCPackType").toString()).trim());
				pstmt.setString(126, StringUtil.checkNull(sendList.get("spRLCTolerance").toString()).trim());
				pstmt.setString(127, StringUtil.checkNull(sendList.get("spFestPrevent").toString()).trim());
				pstmt.setString(128, StringUtil.checkNull(sendList.get("spConnCombDir").toString()).trim());
				pstmt.setString(129, StringUtil.checkNull(sendList.get("spCertified").toString()).trim());
				pstmt.setString(130, StringUtil.checkNull(sendList.get("spPackageSpec").toString()).trim());
				pstmt.setString(131, StringUtil.checkNull(sendList.get("spTabSize").toString()).trim());
				pstmt.setString(132, StringUtil.checkNull(sendList.get("spSealType").toString()).trim());
				pstmt.setString(133, StringUtil.checkNull(sendList.get("spStudSize").toString()).trim());
				pstmt.setString(134, StringUtil.checkNull(sendList.get("spPitch").toString()).trim());
				pstmt.setString(135, StringUtil.checkNull(sendList.get("spSoldering").toString()).trim());
				pstmt.setString(136, StringUtil.checkNull(sendList.get("spConstrucMeth").toString()).trim());
				pstmt.setString(137, StringUtil.checkNull(sendList.get("spOptimumTemp").toString()).trim());
				pstmt.setString(138, StringUtil.checkNull(sendList.get("spContactRes").toString()).trim());
				pstmt.setString(139, StringUtil.checkNull(sendList.get("spInsulatRes").toString()).trim());
				pstmt.setString(140, StringUtil.checkNull(sendList.get("spConntHeight").toString()).trim());
				pstmt.setString(141, StringUtil.checkNull(sendList.get("spCableConMeth").toString()).trim());
				pstmt.setString(142, StringUtil.checkNull(sendList.get("spTerminalType").toString()).trim());
				pstmt.setString(143, StringUtil.checkNull(sendList.get("spTermBarrelSz").toString()).trim());
				pstmt.setString(144, StringUtil.checkNull(sendList.get("spTermPrezType").toString()).trim());
				pstmt.setString(145, StringUtil.checkNull(sendList.get("spGWITMaterAt").toString()).trim());
				pstmt.setString(146, StringUtil.checkNull(sendList.get("spInterface").toString()).trim());
				pstmt.setString(147, StringUtil.checkNull(sendList.get("spPinNShape").toString()).trim());
				pstmt.setString(148, StringUtil.checkNull(sendList.get("spSUBSuppliy").toString()).trim());
				pstmt.setString(149, StringUtil.checkNull(sendList.get("spCodingNColor").toString()).trim());
				pstmt.setString(150, StringUtil.checkNull(sendList.get("spPlant").toString()).trim());
				pstmt.setString(151, StringUtil.checkNull(sendList.get("spPuchaseGroup").toString()).trim());
				pstmt.setString(152, StringUtil.checkNull(sendList.get("spDevManNm").toString()).trim());
				pstmt.setString(153, StringUtil.checkNull(sendList.get("spDesignManNm").toString()).trim());
				pstmt.setString(154, StringUtil.checkNull(sendList.get("spManufacManNm").toString()).trim());
				pstmt.setString(155, StringUtil.checkNull(sendList.get("spMContractSAt").toString()).trim());
				pstmt.setString(156, StringUtil.checkNull(sendList.get("spMMoldAt").toString()).trim());
				pstmt.setString(157, StringUtil.checkNull(sendList.get("spMMakingAt").toString()).trim());
				pstmt.setString(158, StringUtil.checkNull(sendList.get("spMProdAt").toString()).trim());
				pstmt.setString(159, StringUtil.checkNull(sendList.get("spDieWhere").toString()).trim());
				pstmt.setString(160, StringUtil.checkNull(sendList.get("spObjectiveCT").toString()).trim());
				pstmt.setString(161, StringUtil.checkNull(sendList.get("spCavityStd").toString()).trim());
				pstmt.setString(162, StringUtil.checkNull(sendList.get("spMountWayApE").toString()).trim());
				pstmt.setString(163, StringUtil.checkNull(sendList.get("spThickWH").toString()).trim());
				pstmt.setString(164, StringUtil.checkNull(sendList.get("spPropEtc").toString()).trim());
				pstmt.setString(165, StringUtil.checkNull(sendList.get("spHighVoltageSensingLimit").toString()).trim());
				pstmt.setString(166, StringUtil.checkNull(sendList.get("spMovVoltage").toString()).trim());
				pstmt.setString(167, StringUtil.checkNull(sendList.get("spToleranceSensing").toString()).trim());
				pstmt.setString(168, StringUtil.checkNull(sendList.get("spEsirApprove").toString()).trim());
				pstmt.setString(169, StringUtil.checkNull(sendList.get("spMainChipset").toString()).trim());
				pstmt.setString(170, StringUtil.checkNull(sendList.get("spFrequency").toString()).trim());
				pstmt.setString(171, StringUtil.checkNull(sendList.get("spDcpower").toString()).trim());
				pstmt.setString(172, StringUtil.checkNull(sendList.get("spInterfaceIt").toString()).trim());
				pstmt.setString(173, StringUtil.checkNull(sendList.get("spFeatures").toString()).trim());
				pstmt.setString(174, StringUtil.checkNull(sendList.get("spDevSpec").toString()).trim());
				pstmt.setString(175, StringUtil.checkNull(sendList.get("spFlameLevel").toString()).trim());
				pstmt.setString(176, StringUtil.checkNull(sendList.get("spERatedVoltage").toString()).trim());
				pstmt.setString(177, StringUtil.checkNull(sendList.get("spQCNo").toString()).trim());
				pstmt.setString(178, StringUtil.checkNull(sendList.get("spActuatorLctn").toString()).trim());
				pstmt.setString(179, StringUtil.checkNull(sendList.get("spMaxFrequency").toString()).trim());
				pstmt.setString(180, StringUtil.checkNull(sendList.get("spImpedance").toString()).trim());
				pstmt.setString(181, StringUtil.checkNull(sendList.get("spAssemblyMaterial").toString()).trim());
				pstmt.setString(182, StringUtil.checkNull(sendList.get("spDescription").toString()).trim());
				pstmt.setString(183, StringUtil.checkNull(sendList.get("spImgFile").toString()).trim());
				pstmt.setString(184, StringUtil.checkNull(sendList.get("sp2DpdfFile").toString()).trim());
				pstmt.setString(185, StringUtil.checkNull(sendList.get("sp3DpdfFile").toString()).trim());
				pstmt.setString(186, StringUtil.checkNull(sendList.get("spStepFile").toString()).trim());
				pstmt.setString(187, StringUtil.checkNull(sendList.get("spIgsFile").toString()).trim());
				pstmt.setString(188, StringUtil.checkNull(sendList.get("spInstructionsFile").toString()).trim());
				pstmt.setString(189, "N");
				pstmt.setString(190, StringUtil.checkNull(sendList.get("spMasterName").toString()).trim());
				pstmt.setString(191, StringUtil.checkNull(sendList.get("spMasterEmail").toString()).trim());

				pstmt.setString(192, StringUtil.checkNull(sendList.get("spCategoryCode").toString()).trim());
				pstmt.setString(193, StringUtil.checkNull(sendList.get("spClassification").toString()).trim());
				pstmt.setString(194, StringUtil.checkNull(sendList.get("PartName").toString()).trim());
				pstmt.setString(195, StringUtil.checkNull(sendList.get("sPartNumberDrawingNumber").toString()).trim());
				pstmt.setString(196, StringUtil.checkNull(sendList.get("spDivision").toString()).trim());
				pstmt.setString(197, StringUtil.checkNull(sendList.get("spProjectNo").toString()).trim());
				pstmt.setString(198, StringUtil.checkNull(sendList.get("spEoNo").toString()).trim());
				pstmt.setString(199, StringUtil.checkNull(sendList.get("spPartStyle").toString()).trim());
				pstmt.setString(200, StringUtil.checkNull(sendList.get("spPartNameHis").toString()).trim());
				pstmt.setString(201, StringUtil.checkNull(sendList.get("spPartRevision").toString()).trim());
				pstmt.setString(202, StringUtil.checkNull(sendList.get("spPartType").toString()).trim());
				pstmt.setString(203, StringUtil.checkNull(sendList.get("spPartDevLevel").toString()).trim());
				pstmt.setString(204, StringUtil.checkNull(sendList.get("spIsDeleted").toString()).trim());
				pstmt.setString(205, StringUtil.checkNull(sendList.get("spBOMFlag").toString()).trim());
				pstmt.setString(206, StringUtil.checkNull(sendList.get("spWeightUnit").toString()).trim());
				pstmt.setString(207, StringUtil.checkNull(sendList.get("spNetWeight").toString()).trim());
				pstmt.setString(208, StringUtil.checkNull(sendList.get("spTotalWeight").toString()).trim());
				pstmt.setString(209, StringUtil.checkNull(sendList.get("spScrabWeight").toString()).trim());
				pstmt.setString(210, StringUtil.checkNull(sendList.get("spIsYazaki").toString()).trim());
				pstmt.setString(211, StringUtil.checkNull(sendList.get("spYazakiNo").toString()).trim());
				pstmt.setString(212, StringUtil.checkNull(sendList.get("spManufAt").toString()).trim());
				pstmt.setString(213, StringUtil.checkNull(sendList.get("spManufacPlace").toString()).trim());
				pstmt.setString(214, StringUtil.checkNull(sendList.get("spCustomRev").toString()).trim());
				pstmt.setString(215, StringUtil.checkNull(sendList.get("spScrabCode").toString()).trim());
				pstmt.setString(216, StringUtil.checkNull(sendList.get("spWaterProof").toString()).trim());
				pstmt.setString(217, StringUtil.checkNull(sendList.get("spMaterialMark").toString()).trim());
				pstmt.setString(218, StringUtil.checkNull(sendList.get("spColor").toString()).trim());
				pstmt.setString(219, StringUtil.checkNull(sendList.get("spColorPurch").toString()).trim());
				pstmt.setString(220, StringUtil.checkNull(sendList.get("spColorElec").toString()).trim());
				pstmt.setString(221, StringUtil.checkNull(sendList.get("spSeries").toString()).trim());
				pstmt.setString(222, StringUtil.checkNull(sendList.get("spSeriesLAMP").toString()).trim());
				pstmt.setString(223, StringUtil.checkNull(sendList.get("spSeriesBulb").toString()).trim());
				pstmt.setString(224, StringUtil.checkNull(sendList.get("spProdSize").toString()).trim());
				pstmt.setString(225, StringUtil.checkNull(sendList.get("spEnvFriend").toString()).trim());
				pstmt.setString(226, StringUtil.checkNull(sendList.get("spTGenConn").toString()).trim());
				pstmt.setString(227, StringUtil.checkNull(sendList.get("spTPCBConn").toString()).trim());
				pstmt.setString(228, StringUtil.checkNull(sendList.get("spTLAMPConn").toString()).trim());
				pstmt.setString(229, StringUtil.checkNull(sendList.get("spTBulbConn").toString()).trim());
				pstmt.setString(230, StringUtil.checkNull(sendList.get("spTHiVolt").toString()).trim());
				pstmt.setString(231, StringUtil.checkNull(sendList.get("spTCharger").toString()).trim());
				pstmt.setString(232, StringUtil.checkNull(sendList.get("spT2Charger").toString()).trim());
				pstmt.setString(233, StringUtil.checkNull(sendList.get("spT1HiVoltFuz").toString()).trim());
				pstmt.setString(234, StringUtil.checkNull(sendList.get("spTHiVoltFuse").toString()).trim());
				pstmt.setString(235, StringUtil.checkNull(sendList.get("spTJnB").toString()).trim());
				pstmt.setString(236, StringUtil.checkNull(sendList.get("spTPRA").toString()).trim());
				pstmt.setString(237, StringUtil.checkNull(sendList.get("spTGNSS").toString()).trim());
				pstmt.setString(238, StringUtil.checkNull(sendList.get("spTComModule").toString()).trim());
				pstmt.setString(239, StringUtil.checkNull(sendList.get("spTMultiMedUnit").toString()).trim());
				pstmt.setString(240, StringUtil.checkNull(sendList.get("spLanceType").toString()).trim());
				pstmt.setString(241, StringUtil.checkNull(sendList.get("spNoOfPole").toString()).trim());
				pstmt.setString(242, StringUtil.checkNull(sendList.get("spMTerminal").toString()).trim());
				pstmt.setString(243, StringUtil.checkNull(sendList.get("spMConnector").toString()).trim());
				pstmt.setString(244, StringUtil.checkNull(sendList.get("spMatchBulb").toString()).trim());
				pstmt.setString(245, StringUtil.checkNull(sendList.get("spMClip").toString()).trim());
				pstmt.setString(246, StringUtil.checkNull(sendList.get("spMRH").toString()).trim());
				pstmt.setString(247, StringUtil.checkNull(sendList.get("spMCover").toString()).trim());
				pstmt.setString(248, StringUtil.checkNull(sendList.get("spLockingType").toString()).trim());
				pstmt.setString(249, StringUtil.checkNull(sendList.get("spLockTTML").toString()).trim());
				pstmt.setString(250, StringUtil.checkNull(sendList.get("spLockTConn").toString()).trim());
				pstmt.setString(251, StringUtil.checkNull(sendList.get("spMWireSeal").toString()).trim());
				pstmt.setString(252, StringUtil.checkNull(sendList.get("spRepresentM").toString()).trim());
				pstmt.setString(253, StringUtil.checkNull(sendList.get("spMaterMaker").toString()).trim());
				pstmt.setString(254, StringUtil.checkNull(sendList.get("spMaterType").toString()).trim());
				pstmt.setString(255, StringUtil.checkNull(sendList.get("spMaterialInfo").toString()).trim());
				pstmt.setString(256, StringUtil.checkNull(sendList.get("spMaterNotFe").toString()).trim());
				pstmt.setString(257, StringUtil.checkNull(sendList.get("spMaterDie").toString()).trim());
				pstmt.setString(258, StringUtil.checkNull(sendList.get("spMaterPurch").toString()).trim());
				pstmt.setString(259, StringUtil.checkNull(sendList.get("spPlating").toString()).trim());
				pstmt.setString(260, StringUtil.checkNull(sendList.get("spPlatingPurch").toString()).trim());
				pstmt.setString(261, StringUtil.checkNull(sendList.get("spCustomPartNo").toString()).trim());
				pstmt.setString(262, StringUtil.checkNull(sendList.get("spPermitVolt").toString()).trim());
				pstmt.setString(263, StringUtil.checkNull(sendList.get("spWireRangeAWG").toString()).trim());
				pstmt.setString(264, StringUtil.checkNull(sendList.get("spWireRAWGElec").toString()).trim());
				pstmt.setString(265, StringUtil.checkNull(sendList.get("spWireRangeMm").toString()).trim());
				pstmt.setString(266, StringUtil.checkNull(sendList.get("spTabThickness").toString()).trim());
				pstmt.setString(267, StringUtil.checkNull(sendList.get("spMaterThick").toString()).trim());
				pstmt.setString(268, StringUtil.checkNull(sendList.get("spBracketSizeD").toString()).trim());
				pstmt.setString(269, StringUtil.checkNull(sendList.get("spBracketSizeH").toString()).trim());
				pstmt.setString(270, StringUtil.checkNull(sendList.get("spBracketSizeT").toString()).trim());
				pstmt.setString(271, StringUtil.checkNull(sendList.get("spRelayCapa").toString()).trim());
				pstmt.setString(272, StringUtil.checkNull(sendList.get("spEResistVal").toString()).trim());
				pstmt.setString(273, StringUtil.checkNull(sendList.get("spVoltSensCapa").toString()).trim());
				pstmt.setString(274, StringUtil.checkNull(sendList.get("spManufPartNo").toString()).trim());
				pstmt.setString(275, StringUtil.checkNull(sendList.get("spValueValue").toString()).trim());
				pstmt.setString(276, StringUtil.checkNull(sendList.get("spTolerance").toString()).trim());
				pstmt.setString(277, StringUtil.checkNull(sendList.get("spManufacturer").toString()).trim());
				pstmt.setString(278, StringUtil.checkNull(sendList.get("spRatedVoltage").toString()).trim());
				pstmt.setString(279, StringUtil.checkNull(sendList.get("spWatt").toString()).trim());
				pstmt.setString(280, StringUtil.checkNull(sendList.get("spOperTemp").toString()).trim());
				pstmt.setString(281, StringUtil.checkNull(sendList.get("spStoreTemp").toString()).trim());
				pstmt.setString(282, StringUtil.checkNull(sendList.get("spPackageType").toString()).trim());
				pstmt.setString(283, StringUtil.checkNull(sendList.get("spMSL").toString()).trim());
				pstmt.setString(284, StringUtil.checkNull(sendList.get("spESD").toString()).trim());
				pstmt.setString(285, StringUtil.checkNull(sendList.get("spAECQ").toString()).trim());
				pstmt.setString(286, StringUtil.checkNull(sendList.get("spCharact1").toString()).trim());
				pstmt.setString(287, StringUtil.checkNull(sendList.get("spCharact2").toString()).trim());
				pstmt.setString(288, StringUtil.checkNull(sendList.get("spHoleSize").toString()).trim());
				pstmt.setString(289, StringUtil.checkNull(sendList.get("spWireRangeSQ").toString()).trim());
				pstmt.setString(290, StringUtil.checkNull(sendList.get("spWATTW").toString()).trim());
				pstmt.setString(291, StringUtil.checkNull(sendList.get("spSizemm").toString()).trim());
				pstmt.setString(292, StringUtil.checkNull(sendList.get("spPermitTempC").toString()).trim());
				pstmt.setString(293, StringUtil.checkNull(sendList.get("spIsResin").toString()).trim());
				pstmt.setString(294, StringUtil.checkNull(sendList.get("spThickness").toString()).trim());
				pstmt.setString(295, StringUtil.checkNull(sendList.get("spHoleShape").toString()).trim());
				pstmt.setString(296, StringUtil.checkNull(sendList.get("spCapaEResist").toString()).trim());
				pstmt.setString(297, StringUtil.checkNull(sendList.get("spClothesMater").toString()).trim());
				pstmt.setString(298, StringUtil.checkNull(sendList.get("spIsShield").toString()).trim());
				pstmt.setString(299, StringUtil.checkNull(sendList.get("spESIRApproval").toString()).trim());
				pstmt.setString(300, StringUtil.checkNull(sendList.get("spISIRApproval").toString()).trim());
				pstmt.setString(301, StringUtil.checkNull(sendList.get("spConAppNoESIR").toString()).trim());
				pstmt.setString(302, StringUtil.checkNull(sendList.get("spLayer").toString()).trim());
				pstmt.setString(303, StringUtil.checkNull(sendList.get("spOrgDskPartNo").toString()).trim());
				pstmt.setString(304, StringUtil.checkNull(sendList.get("spPCBMaterial").toString()).trim());
				pstmt.setString(305, StringUtil.checkNull(sendList.get("spTg").toString()).trim());
				pstmt.setString(306, StringUtil.checkNull(sendList.get("spCharact").toString()).trim());
				pstmt.setString(307, StringUtil.checkNull(sendList.get("spSurfaceTreat").toString()).trim());
				pstmt.setString(308, StringUtil.checkNull(sendList.get("spAppearanProc").toString()).trim());
				pstmt.setString(309, StringUtil.checkNull(sendList.get("spSoldResColor").toString()).trim());
				pstmt.setString(310, StringUtil.checkNull(sendList.get("spInstallPos").toString()).trim());
				pstmt.setString(311, StringUtil.checkNull(sendList.get("spSwVersion").toString()).trim());
				pstmt.setString(312, StringUtil.checkNull(sendList.get("spUnitUnit").toString()).trim());
				pstmt.setString(313, StringUtil.checkNull(sendList.get("spResUnit").toString()).trim());
				pstmt.setString(314, StringUtil.checkNull(sendList.get("spINDUnit").toString()).trim());
				pstmt.setString(315, StringUtil.checkNull(sendList.get("spCapUnit").toString()).trim());
				pstmt.setString(316, StringUtil.checkNull(sendList.get("spRLCPackType").toString()).trim());
				pstmt.setString(317, StringUtil.checkNull(sendList.get("spRLCTolerance").toString()).trim());
				pstmt.setString(318, StringUtil.checkNull(sendList.get("spFestPrevent").toString()).trim());
				pstmt.setString(319, StringUtil.checkNull(sendList.get("spConnCombDir").toString()).trim());
				pstmt.setString(320, StringUtil.checkNull(sendList.get("spCertified").toString()).trim());
				pstmt.setString(321, StringUtil.checkNull(sendList.get("spPackageSpec").toString()).trim());
				pstmt.setString(322, StringUtil.checkNull(sendList.get("spTabSize").toString()).trim());
				pstmt.setString(323, StringUtil.checkNull(sendList.get("spSealType").toString()).trim());
				pstmt.setString(324, StringUtil.checkNull(sendList.get("spStudSize").toString()).trim());
				pstmt.setString(325, StringUtil.checkNull(sendList.get("spPitch").toString()).trim());
				pstmt.setString(326, StringUtil.checkNull(sendList.get("spSoldering").toString()).trim());
				pstmt.setString(327, StringUtil.checkNull(sendList.get("spConstrucMeth").toString()).trim());
				pstmt.setString(328, StringUtil.checkNull(sendList.get("spOptimumTemp").toString()).trim());
				pstmt.setString(329, StringUtil.checkNull(sendList.get("spContactRes").toString()).trim());
				pstmt.setString(330, StringUtil.checkNull(sendList.get("spInsulatRes").toString()).trim());
				pstmt.setString(331, StringUtil.checkNull(sendList.get("spConntHeight").toString()).trim());
				pstmt.setString(332, StringUtil.checkNull(sendList.get("spCableConMeth").toString()).trim());
				pstmt.setString(333, StringUtil.checkNull(sendList.get("spTerminalType").toString()).trim());
				pstmt.setString(334, StringUtil.checkNull(sendList.get("spTermBarrelSz").toString()).trim());
				pstmt.setString(335, StringUtil.checkNull(sendList.get("spTermPrezType").toString()).trim());
				pstmt.setString(336, StringUtil.checkNull(sendList.get("spGWITMaterAt").toString()).trim());
				pstmt.setString(337, StringUtil.checkNull(sendList.get("spInterface").toString()).trim());
				pstmt.setString(338, StringUtil.checkNull(sendList.get("spPinNShape").toString()).trim());
				pstmt.setString(339, StringUtil.checkNull(sendList.get("spSUBSuppliy").toString()).trim());
				pstmt.setString(340, StringUtil.checkNull(sendList.get("spCodingNColor").toString()).trim());
				pstmt.setString(341, StringUtil.checkNull(sendList.get("spPlant").toString()).trim());
				pstmt.setString(342, StringUtil.checkNull(sendList.get("spPuchaseGroup").toString()).trim());
				pstmt.setString(343, StringUtil.checkNull(sendList.get("spDevManNm").toString()).trim());
				pstmt.setString(344, StringUtil.checkNull(sendList.get("spDesignManNm").toString()).trim());
				pstmt.setString(345, StringUtil.checkNull(sendList.get("spManufacManNm").toString()).trim());
				pstmt.setString(346, StringUtil.checkNull(sendList.get("spMContractSAt").toString()).trim());
				pstmt.setString(347, StringUtil.checkNull(sendList.get("spMMoldAt").toString()).trim());
				pstmt.setString(348, StringUtil.checkNull(sendList.get("spMMakingAt").toString()).trim());
				pstmt.setString(349, StringUtil.checkNull(sendList.get("spMProdAt").toString()).trim());
				pstmt.setString(350, StringUtil.checkNull(sendList.get("spDieWhere").toString()).trim());
				pstmt.setString(351, StringUtil.checkNull(sendList.get("spObjectiveCT").toString()).trim());
				pstmt.setString(352, StringUtil.checkNull(sendList.get("spCavityStd").toString()).trim());
				pstmt.setString(353, StringUtil.checkNull(sendList.get("spMountWayApE").toString()).trim());
				pstmt.setString(354, StringUtil.checkNull(sendList.get("spThickWH").toString()).trim());
				pstmt.setString(355, StringUtil.checkNull(sendList.get("spPropEtc").toString()).trim());
				pstmt.setString(356, StringUtil.checkNull(sendList.get("spHighVoltageSensingLimit").toString()).trim());
				pstmt.setString(357, StringUtil.checkNull(sendList.get("spMovVoltage").toString()).trim());
				pstmt.setString(358, StringUtil.checkNull(sendList.get("spToleranceSensing").toString()).trim());
				pstmt.setString(359, StringUtil.checkNull(sendList.get("spEsirApprove").toString()).trim());
				pstmt.setString(360, StringUtil.checkNull(sendList.get("spMainChipset").toString()).trim());
				pstmt.setString(361, StringUtil.checkNull(sendList.get("spFrequency").toString()).trim());
				pstmt.setString(362, StringUtil.checkNull(sendList.get("spDcpower").toString()).trim());
				pstmt.setString(363, StringUtil.checkNull(sendList.get("spInterfaceIt").toString()).trim());
				pstmt.setString(364, StringUtil.checkNull(sendList.get("spFeatures").toString()).trim());
				pstmt.setString(365, StringUtil.checkNull(sendList.get("spDevSpec").toString()).trim());
				pstmt.setString(366, StringUtil.checkNull(sendList.get("spFlameLevel").toString()).trim());
				pstmt.setString(367, StringUtil.checkNull(sendList.get("spERatedVoltage").toString()).trim());
				pstmt.setString(368, StringUtil.checkNull(sendList.get("spQCNo").toString()).trim());
				pstmt.setString(369, StringUtil.checkNull(sendList.get("spActuatorLctn").toString()).trim());
				pstmt.setString(370, StringUtil.checkNull(sendList.get("spMaxFrequency").toString()).trim());
				pstmt.setString(371, StringUtil.checkNull(sendList.get("spImpedance").toString()).trim());
				pstmt.setString(372, StringUtil.checkNull(sendList.get("spAssemblyMaterial").toString()).trim());
				pstmt.setString(373, StringUtil.checkNull(sendList.get("spDescription").toString()).trim());
				pstmt.setString(374, StringUtil.checkNull(sendList.get("spImgFile").toString()).trim());
				pstmt.setString(375, StringUtil.checkNull(sendList.get("sp2DpdfFile").toString()).trim());
				pstmt.setString(376, StringUtil.checkNull(sendList.get("sp3DpdfFile").toString()).trim());
				pstmt.setString(377, StringUtil.checkNull(sendList.get("spStepFile").toString()).trim());
				pstmt.setString(378, StringUtil.checkNull(sendList.get("spIgsFile").toString()).trim());
				pstmt.setString(379, StringUtil.checkNull(sendList.get("spInstructionsFile").toString()).trim());
				pstmt.setString(380, "N");
				pstmt.setString(381, StringUtil.checkNull(sendList.get("spMasterName").toString()).trim());
				pstmt.setString(382, StringUtil.checkNull(sendList.get("spMasterEmail").toString()).trim());

				complet = pstmt.executeUpdate();

				sb.delete(0, sb.length());
			}

		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (pstmt != null) {
				pstmt.close();
			}

		}
		return complet;
	}

	public int savePlmHpIfMig(List<Map<String, Object>> distReqEpmDocList) throws Exception {
		PreparedStatement pstmt = null;
		int complet = 0;
		try {
			StringBuilder sb = new StringBuilder();

			for (Map<String, Object> sendList : distReqEpmDocList) {
				// KETPLM.dbo.WKET_IF001
				// sb.append(" INSERT INTO KETPLM.dbo.WKET_IF001 ");
				// sb.append("\n (	spCategoryCode,spClassification,PartName,PartNumber,spDivision,spProjectNo,spEoNo,spPartStyle,spPartNameHis,spPartRevision,");
				// sb.append("\n 	spPartType,spPartDevLevel,spIsDeleted,spBOMFlag,spWeightUnit,spNetWeight,spTotalWeight,spScrabWeight,spIsYazaki,");
				// sb.append("\n 	spYazakiNo,spManufAt,spManufacPlace,spCustomRev,spScrabCode,spWaterProof,spMaterialMark,spColor,spColorPurch,");
				// sb.append("\n 	spColorElec,spSeries,spSeriesLAMP,spSeriesBulb,spProdSize,spEnvFriend,spTGenConn,spTPCBConn,spTLAMPConn,spTBulbConn,");
				// sb.append("\n 	spTHiVolt,spTCharger,spT2Charger,spT1HiVoltFuz,spTHiVoltFuse,spTJnB,spTPRA,spTGNSS,spTComModule,spTMultiMedUnit,");
				// sb.append("\n 	spLanceType,spNoOfPole,spMTerminal,spMConnector,spMatchBulb,spMClip,spMRH,spMCover,spLockingType,spLockTTML,");
				// sb.append("\n 	spLockTConn,spMWireSeal,spRepresentM,spMaterMaker,spMaterType,spMaterialInfo,spMaterNotFe,spMaterDie,spMaterPurch,");
				// sb.append("\n 	spPlating,spPlatingPurch,spCustomPartNo,spPermitVolt,spWireRangeAWG,spWireRAWGElec,spWireRangeMm,spTabThickness,");
				// sb.append("\n 	spMaterThick,spBracketSizeD,spBracketSizeH,spBracketSizeT,spRelayCapa,spEResistVal,spVoltSensCapa,spManufPartNo,");
				// sb.append("\n 	spValueValue,spTolerance,spManufacturer,spRatedVoltage,spWatt,spOperTemp,spStoreTemp,spPackageType,spMSL,spESD,");
				// sb.append("\n 	spAECQ,spCharact1,spCharact2,spHoleSize,spWireRangeSQ,spWATTW,spSizemm,spPermitTempC,spIsResin,spThickness,spHoleShape,");
				// sb.append("\n 	spCapaEResist,spClothesMater,spIsShield,spESIRApproval,spISIRApproval,spConAppNoESIR,spLayer,spOrgDskPartNo,spPCBMaterial,");
				// sb.append("\n 	spTg,spCharact,spSurfaceTreat,spAppearanProc,spSoldResColor,spInstallPos,spSwVersion,spUnitUnit,spResUnit,spINDUnit,");
				// sb.append("\n 	spCapUnit,spRLCPackType,spRLCTolerance,spFestPrevent,spConnCombDir,spCertified,spPackageSpec,spTabSize,spSealType,");
				// sb.append("\n 	spStudSize,spPitch,spSoldering,spConstrucMeth,spOptimumTemp,spContactRes,spInsulatRes,spConntHeight,spCableConMeth,");
				// sb.append("\n 	spTerminalType,spTermBarrelSz,spTermPrezType,spGWITMaterAt,spInterface,spPinNShape,spSUBSuppliy,spCodingNColor,");
				// sb.append("\n 	spPlant,spPuchaseGroup,spDevManNm,spDesignManNm,spManufacManNm,spMContractSAt,spMMoldAt,spMMakingAt,spMProdAt,");
				// sb.append("\n 	spDieWhere,spObjectiveCT,spCavityStd,spMountWayApE,spThickWH,spPropEtc,spHighVoltageSensingLimit,spMovVoltage,");
				// sb.append("\n 	spToleranceSensing,spEsirApprove,spMainChipset,spFrequency,spDcpower,spInterfaceIt,spFeatures,spDevSpec,");
				// sb.append("\n 	spFlameLevel,spERatedVoltage,spQCNo,spActuatorLctn,spMaxFrequency,spImpedance,spAssemblyMaterial,spDescription,");
				// sb.append("\n 	spImgFile,sp2DpdfFile,sp3DpdfFile,spStepFile,spIgsFile,spInstructionsFile,USE_YN,spMasterName,spMasterEmail, RGST_DTM");
				// sb.append("\n )");
				// sb.append("\n VALUES");
				// sb.append("\n (");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				// sb.append(" ?, GETDATE() )");
				System.out.println("by hooni ::: ==================>" + StringUtil.checkNull(sendList.get("HpPartNumber").toString()).trim());
				sb.append(" MERGE KETPLM.dbo.WKET_IF001 A \n");
				sb.append(" USING (SELECT '" + StringUtil.checkNull(sendList.get("HpPartNumber").toString()).trim() + "' AS PartNumber) AS B");
				sb.append(" ON (A.PartNumber = B.PartNumber) \n");
				sb.append(" WHEN MATCHED THEN \n");
				sb.append(" UPDATE SET \n ");
				sb.append("\n 	spCategoryCode=?,spClassification=?,PartName=?,PartNumber=?,spDivision=?,spProjectNo=?,spEoNo=?,spPartStyle=?,spPartNameHis=?,spPartRevision=?,");
				sb.append("\n 	spPartType=?,spPartDevLevel=?,spIsDeleted=?,spBOMFlag=?,spWeightUnit=?,spNetWeight=?,spTotalWeight=?,spScrabWeight=?,spIsYazaki=?,");
				sb.append("\n 	spYazakiNo=?,spManufAt=?,spManufacPlace=?,spCustomRev=?,spScrabCode=?,spWaterProof=?,spMaterialMark=?,spColor=?,spColorPurch=?,");
				sb.append("\n 	spColorElec=?,spSeries=?,spSeriesLAMP=?,spSeriesBulb=?,spProdSize=?,spEnvFriend=?,spTGenConn=?,spTPCBConn=?,spTLAMPConn=?,spTBulbConn=?,");
				sb.append("\n 	spTHiVolt=?,spTCharger=?,spT2Charger=?,spT1HiVoltFuz=?,spTHiVoltFuse=?,spTJnB=?,spTPRA=?,spTGNSS=?,spTComModule=?,spTMultiMedUnit=?,");
				sb.append("\n 	spLanceType=?,spNoOfPole=?,spMTerminal=?,spMConnector=?,spMatchBulb=?,spMClip=?,spMRH=?,spMCover=?,spLockingType=?,spLockTTML=?,");
				sb.append("\n 	spLockTConn=?,spMWireSeal=?,spRepresentM=?,spMaterMaker=?,spMaterType=?,spMaterialInfo=?,spMaterNotFe=?,spMaterDie=?,spMaterPurch=?,");
				sb.append("\n 	spPlating=?,spPlatingPurch=?,spCustomPartNo=?,spPermitVolt=?,spWireRangeAWG=?,spWireRAWGElec=?,spWireRangeMm=?,spTabThickness=?,");
				sb.append("\n 	spMaterThick=?,spBracketSizeD=?,spBracketSizeH=?,spBracketSizeT=?,spRelayCapa=?,spEResistVal=?,spVoltSensCapa=?,spManufPartNo=?,");
				sb.append("\n 	spValueValue=?,spTolerance=?,spManufacturer=?,spRatedVoltage=?,spWatt=?,spOperTemp=?,spStoreTemp=?,spPackageType=?,spMSL=?,spESD=?,");
				sb.append("\n 	spAECQ=?,spCharact1=?,spCharact2=?,spHoleSize=?,spWireRangeSQ=?,spWATTW=?,spSizemm=?,spPermitTempC=?,spIsResin=?,spThickness=?,spHoleShape=?,");
				sb.append("\n 	spCapaEResist=?,spClothesMater=?,spIsShield=?,spESIRApproval=?,spISIRApproval=?,spConAppNoESIR=?,spLayer=?,spOrgDskPartNo=?,spPCBMaterial=?,");
				sb.append("\n 	spTg=?,spCharact=?,spSurfaceTreat=?,spAppearanProc=?,spSoldResColor=?,spInstallPos=?,spSwVersion=?,spUnitUnit=?,spResUnit=?,spINDUnit=?,");
				sb.append("\n 	spCapUnit=?,spRLCPackType=?,spRLCTolerance=?,spFestPrevent=?,spConnCombDir=?,spCertified=?,spPackageSpec=?,spTabSize=?,spSealType=?,");
				sb.append("\n 	spStudSize=?,spPitch=?,spSoldering=?,spConstrucMeth=?,spOptimumTemp=?,spContactRes=?,spInsulatRes=?,spConntHeight=?,spCableConMeth=?,");
				sb.append("\n 	spTerminalType=?,spTermBarrelSz=?,spTermPrezType=?,spGWITMaterAt=?,spInterface=?,spPinNShape=?,spSUBSuppliy=?,spCodingNColor=?,");
				sb.append("\n 	spPlant=?,spPuchaseGroup=?,spDevManNm=?,spDesignManNm=?,spManufacManNm=?,spMContractSAt=?,spMMoldAt=?,spMMakingAt=?,spMProdAt=?,");
				sb.append("\n 	spDieWhere=?,spObjectiveCT=?,spCavityStd=?,spMountWayApE=?,spThickWH=?,spPropEtc=?,spHighVoltageSensingLimit=?,spMovVoltage=?,");
				sb.append("\n 	spToleranceSensing=?,spEsirApprove=?,spMainChipset=?,spFrequency=?,spDcpower=?,spInterfaceIt=?,spFeatures=?,spDevSpec=?,");
				sb.append("\n 	spFlameLevel=?,spERatedVoltage=?,spQCNo=?,spActuatorLctn=?,spMaxFrequency=?,spImpedance=?,spAssemblyMaterial=?,spDescription=?,");
				sb.append("\n 	spImgFile=?,sp2DpdfFile=?,sp3DpdfFile=?,spStepFile=?,spIgsFile=?,spInstructionsFile=?,USE_YN=?,spMasterName=?,spMasterEmail=?, RGST_DTM=GETDATE()");
				sb.append(" WHEN NOT MATCHED THEN \n");
				sb.append(" INSERT ");
				sb.append("\n (	spCategoryCode,spClassification,PartName,PartNumber,spDivision,spProjectNo,spEoNo,spPartStyle,spPartNameHis,spPartRevision,");
				sb.append("\n 	spPartType,spPartDevLevel,spIsDeleted,spBOMFlag,spWeightUnit,spNetWeight,spTotalWeight,spScrabWeight,spIsYazaki,");
				sb.append("\n 	spYazakiNo,spManufAt,spManufacPlace,spCustomRev,spScrabCode,spWaterProof,spMaterialMark,spColor,spColorPurch,");
				sb.append("\n 	spColorElec,spSeries,spSeriesLAMP,spSeriesBulb,spProdSize,spEnvFriend,spTGenConn,spTPCBConn,spTLAMPConn,spTBulbConn,");
				sb.append("\n 	spTHiVolt,spTCharger,spT2Charger,spT1HiVoltFuz,spTHiVoltFuse,spTJnB,spTPRA,spTGNSS,spTComModule,spTMultiMedUnit,");
				sb.append("\n 	spLanceType,spNoOfPole,spMTerminal,spMConnector,spMatchBulb,spMClip,spMRH,spMCover,spLockingType,spLockTTML,");
				sb.append("\n 	spLockTConn,spMWireSeal,spRepresentM,spMaterMaker,spMaterType,spMaterialInfo,spMaterNotFe,spMaterDie,spMaterPurch,");
				sb.append("\n 	spPlating,spPlatingPurch,spCustomPartNo,spPermitVolt,spWireRangeAWG,spWireRAWGElec,spWireRangeMm,spTabThickness,");
				sb.append("\n 	spMaterThick,spBracketSizeD,spBracketSizeH,spBracketSizeT,spRelayCapa,spEResistVal,spVoltSensCapa,spManufPartNo,");
				sb.append("\n 	spValueValue,spTolerance,spManufacturer,spRatedVoltage,spWatt,spOperTemp,spStoreTemp,spPackageType,spMSL,spESD,");
				sb.append("\n 	spAECQ,spCharact1,spCharact2,spHoleSize,spWireRangeSQ,spWATTW,spSizemm,spPermitTempC,spIsResin,spThickness,spHoleShape,");
				sb.append("\n 	spCapaEResist,spClothesMater,spIsShield,spESIRApproval,spISIRApproval,spConAppNoESIR,spLayer,spOrgDskPartNo,spPCBMaterial,");
				sb.append("\n 	spTg,spCharact,spSurfaceTreat,spAppearanProc,spSoldResColor,spInstallPos,spSwVersion,spUnitUnit,spResUnit,spINDUnit,");
				sb.append("\n 	spCapUnit,spRLCPackType,spRLCTolerance,spFestPrevent,spConnCombDir,spCertified,spPackageSpec,spTabSize,spSealType,");
				sb.append("\n 	spStudSize,spPitch,spSoldering,spConstrucMeth,spOptimumTemp,spContactRes,spInsulatRes,spConntHeight,spCableConMeth,");
				sb.append("\n 	spTerminalType,spTermBarrelSz,spTermPrezType,spGWITMaterAt,spInterface,spPinNShape,spSUBSuppliy,spCodingNColor,");
				sb.append("\n 	spPlant,spPuchaseGroup,spDevManNm,spDesignManNm,spManufacManNm,spMContractSAt,spMMoldAt,spMMakingAt,spMProdAt,");
				sb.append("\n 	spDieWhere,spObjectiveCT,spCavityStd,spMountWayApE,spThickWH,spPropEtc,spHighVoltageSensingLimit,spMovVoltage,");
				sb.append("\n 	spToleranceSensing,spEsirApprove,spMainChipset,spFrequency,spDcpower,spInterfaceIt,spFeatures,spDevSpec,");
				sb.append("\n 	spFlameLevel,spERatedVoltage,spQCNo,spActuatorLctn,spMaxFrequency,spImpedance,spAssemblyMaterial,spDescription,");
				sb.append("\n 	spImgFile,sp2DpdfFile,sp3DpdfFile,spStepFile,spIgsFile,spInstructionsFile,USE_YN,spMasterName,spMasterEmail, RGST_DTM");
				sb.append("\n )");
				sb.append("\n VALUES");
				sb.append("\n (");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,");
				sb.append(" ?, GETDATE() );");

				pstmt = conn.prepareStatement(sb.toString());
				pstmt.setString(1, StringUtil.checkNull(sendList.get("spCategoryCode").toString()).trim());
				pstmt.setString(2, StringUtil.checkNull(sendList.get("spClassification").toString()).trim());
				pstmt.setString(3, StringUtil.checkNull(sendList.get("PartName").toString()).trim());
				pstmt.setString(4, StringUtil.checkNull(sendList.get("HpPartNumber").toString()).trim());
				pstmt.setString(5, StringUtil.checkNull(sendList.get("spDivision").toString()).trim());
				pstmt.setString(6, StringUtil.checkNull(sendList.get("spProjectNo").toString()).trim());
				pstmt.setString(7, StringUtil.checkNull(sendList.get("spEoNo").toString()).trim());
				pstmt.setString(8, StringUtil.checkNull(sendList.get("spPartStyle").toString()).trim());
				pstmt.setString(9, StringUtil.checkNull(sendList.get("spPartNameHis").toString()).trim());
				pstmt.setString(10, StringUtil.checkNull(sendList.get("spPartRevision").toString()).trim());
				pstmt.setString(11, StringUtil.checkNull(sendList.get("spPartType").toString()).trim());
				pstmt.setString(12, StringUtil.checkNull(sendList.get("spPartDevLevel").toString()).trim());
				pstmt.setString(13, StringUtil.checkNull(sendList.get("spIsDeleted").toString()).trim());
				pstmt.setString(14, StringUtil.checkNull(sendList.get("spBOMFlag").toString()).trim());
				pstmt.setString(15, StringUtil.checkNull(sendList.get("spWeightUnit").toString()).trim());
				pstmt.setString(16, StringUtil.checkNull(sendList.get("spNetWeight").toString()).trim());
				pstmt.setString(17, StringUtil.checkNull(sendList.get("spTotalWeight").toString()).trim());
				pstmt.setString(18, StringUtil.checkNull(sendList.get("spScrabWeight").toString()).trim());
				pstmt.setString(19, StringUtil.checkNull(sendList.get("spIsYazaki").toString()).trim());
				pstmt.setString(20, StringUtil.checkNull(sendList.get("spYazakiNo").toString()).trim());
				pstmt.setString(21, StringUtil.checkNull(sendList.get("spManufAt").toString()).trim());
				pstmt.setString(22, StringUtil.checkNull(sendList.get("spManufacPlace").toString()).trim());
				pstmt.setString(23, StringUtil.checkNull(sendList.get("spCustomRev").toString()).trim());
				pstmt.setString(24, StringUtil.checkNull(sendList.get("spScrabCode").toString()).trim());
				pstmt.setString(25, StringUtil.checkNull(sendList.get("spWaterProof").toString()).trim());
				pstmt.setString(26, StringUtil.checkNull(sendList.get("spMaterialMark").toString()).trim());
				pstmt.setString(27, StringUtil.checkNull(sendList.get("spColor").toString()).trim());
				pstmt.setString(28, StringUtil.checkNull(sendList.get("spColorPurch").toString()).trim());
				pstmt.setString(29, StringUtil.checkNull(sendList.get("spColorElec").toString()).trim());
				pstmt.setString(30, StringUtil.checkNull(sendList.get("spSeries").toString()).trim());
				pstmt.setString(31, StringUtil.checkNull(sendList.get("spSeriesLAMP").toString()).trim());
				pstmt.setString(32, StringUtil.checkNull(sendList.get("spSeriesBulb").toString()).trim());
				pstmt.setString(33, StringUtil.checkNull(sendList.get("spProdSize").toString()).trim());
				pstmt.setString(34, StringUtil.checkNull(sendList.get("spEnvFriend").toString()).trim());
				pstmt.setString(35, StringUtil.checkNull(sendList.get("spTGenConn").toString()).trim());
				pstmt.setString(36, StringUtil.checkNull(sendList.get("spTPCBConn").toString()).trim());
				pstmt.setString(37, StringUtil.checkNull(sendList.get("spTLAMPConn").toString()).trim());
				pstmt.setString(38, StringUtil.checkNull(sendList.get("spTBulbConn").toString()).trim());
				pstmt.setString(39, StringUtil.checkNull(sendList.get("spTHiVolt").toString()).trim());
				pstmt.setString(40, StringUtil.checkNull(sendList.get("spTCharger").toString()).trim());
				pstmt.setString(41, StringUtil.checkNull(sendList.get("spT2Charger").toString()).trim());
				pstmt.setString(42, StringUtil.checkNull(sendList.get("spT1HiVoltFuz").toString()).trim());
				pstmt.setString(43, StringUtil.checkNull(sendList.get("spTHiVoltFuse").toString()).trim());
				pstmt.setString(44, StringUtil.checkNull(sendList.get("spTJnB").toString()).trim());
				pstmt.setString(45, StringUtil.checkNull(sendList.get("spTPRA").toString()).trim());
				pstmt.setString(46, StringUtil.checkNull(sendList.get("spTGNSS").toString()).trim());
				pstmt.setString(47, StringUtil.checkNull(sendList.get("spTComModule").toString()).trim());
				pstmt.setString(48, StringUtil.checkNull(sendList.get("spTMultiMedUnit").toString()).trim());
				pstmt.setString(49, StringUtil.checkNull(sendList.get("spLanceType").toString()).trim());
				pstmt.setString(50, StringUtil.checkNull(sendList.get("spNoOfPole").toString()).trim());
				pstmt.setString(51, StringUtil.checkNull(sendList.get("spMTerminal").toString()).trim());
				pstmt.setString(52, StringUtil.checkNull(sendList.get("spMConnector").toString()).trim());
				pstmt.setString(53, StringUtil.checkNull(sendList.get("spMatchBulb").toString()).trim());
				pstmt.setString(54, StringUtil.checkNull(sendList.get("spMClip").toString()).trim());
				pstmt.setString(55, StringUtil.checkNull(sendList.get("spMRH").toString()).trim());
				pstmt.setString(56, StringUtil.checkNull(sendList.get("spMCover").toString()).trim());
				pstmt.setString(57, StringUtil.checkNull(sendList.get("spLockingType").toString()).trim());
				pstmt.setString(58, StringUtil.checkNull(sendList.get("spLockTTML").toString()).trim());
				pstmt.setString(59, StringUtil.checkNull(sendList.get("spLockTConn").toString()).trim());
				pstmt.setString(60, StringUtil.checkNull(sendList.get("spMWireSeal").toString()).trim());
				pstmt.setString(61, StringUtil.checkNull(sendList.get("spRepresentM").toString()).trim());
				pstmt.setString(62, StringUtil.checkNull(sendList.get("spMaterMaker").toString()).trim());
				pstmt.setString(63, StringUtil.checkNull(sendList.get("spMaterType").toString()).trim());
				pstmt.setString(64, StringUtil.checkNull(sendList.get("spMaterialInfo").toString()).trim());
				pstmt.setString(65, StringUtil.checkNull(sendList.get("spMaterNotFe").toString()).trim());
				pstmt.setString(66, StringUtil.checkNull(sendList.get("spMaterDie").toString()).trim());
				pstmt.setString(67, StringUtil.checkNull(sendList.get("spMaterPurch").toString()).trim());
				pstmt.setString(68, StringUtil.checkNull(sendList.get("spPlating").toString()).trim());
				pstmt.setString(69, StringUtil.checkNull(sendList.get("spPlatingPurch").toString()).trim());
				pstmt.setString(70, StringUtil.checkNull(sendList.get("spCustomPartNo").toString()).trim());
				pstmt.setString(71, StringUtil.checkNull(sendList.get("spPermitVolt").toString()).trim());
				pstmt.setString(72, StringUtil.checkNull(sendList.get("spWireRangeAWG").toString()).trim());
				pstmt.setString(73, StringUtil.checkNull(sendList.get("spWireRAWGElec").toString()).trim());
				pstmt.setString(74, StringUtil.checkNull(sendList.get("spWireRangeMm").toString()).trim());
				pstmt.setString(75, StringUtil.checkNull(sendList.get("spTabThickness").toString()).trim());
				pstmt.setString(76, StringUtil.checkNull(sendList.get("spMaterThick").toString()).trim());
				pstmt.setString(77, StringUtil.checkNull(sendList.get("spBracketSizeD").toString()).trim());
				pstmt.setString(78, StringUtil.checkNull(sendList.get("spBracketSizeH").toString()).trim());
				pstmt.setString(79, StringUtil.checkNull(sendList.get("spBracketSizeT").toString()).trim());
				pstmt.setString(80, StringUtil.checkNull(sendList.get("spRelayCapa").toString()).trim());
				pstmt.setString(81, StringUtil.checkNull(sendList.get("spEResistVal").toString()).trim());
				pstmt.setString(82, StringUtil.checkNull(sendList.get("spVoltSensCapa").toString()).trim());
				pstmt.setString(83, StringUtil.checkNull(sendList.get("spManufPartNo").toString()).trim());
				pstmt.setString(84, StringUtil.checkNull(sendList.get("spValueValue").toString()).trim());
				pstmt.setString(85, StringUtil.checkNull(sendList.get("spTolerance").toString()).trim());
				pstmt.setString(86, StringUtil.checkNull(sendList.get("spManufacturer").toString()).trim());
				pstmt.setString(87, StringUtil.checkNull(sendList.get("spRatedVoltage").toString()).trim());
				pstmt.setString(88, StringUtil.checkNull(sendList.get("spWatt").toString()).trim());
				pstmt.setString(89, StringUtil.checkNull(sendList.get("spOperTemp").toString()).trim());
				pstmt.setString(90, StringUtil.checkNull(sendList.get("spStoreTemp").toString()).trim());
				pstmt.setString(91, StringUtil.checkNull(sendList.get("spPackageType").toString()).trim());
				pstmt.setString(92, StringUtil.checkNull(sendList.get("spMSL").toString()).trim());
				pstmt.setString(93, StringUtil.checkNull(sendList.get("spESD").toString()).trim());
				pstmt.setString(94, StringUtil.checkNull(sendList.get("spAECQ").toString()).trim());
				pstmt.setString(95, StringUtil.checkNull(sendList.get("spCharact1").toString()).trim());
				pstmt.setString(96, StringUtil.checkNull(sendList.get("spCharact2").toString()).trim());
				pstmt.setString(97, StringUtil.checkNull(sendList.get("spHoleSize").toString()).trim());
				pstmt.setString(98, StringUtil.checkNull(sendList.get("spWireRangeSQ").toString()).trim());
				pstmt.setString(99, StringUtil.checkNull(sendList.get("spWATTW").toString()).trim());
				pstmt.setString(100, StringUtil.checkNull(sendList.get("spSizemm").toString()).trim());
				pstmt.setString(101, StringUtil.checkNull(sendList.get("spPermitTempC").toString()).trim());
				pstmt.setString(102, StringUtil.checkNull(sendList.get("spIsResin").toString()).trim());
				pstmt.setString(103, StringUtil.checkNull(sendList.get("spThickness").toString()).trim());
				pstmt.setString(104, StringUtil.checkNull(sendList.get("spHoleShape").toString()).trim());
				pstmt.setString(105, StringUtil.checkNull(sendList.get("spCapaEResist").toString()).trim());
				pstmt.setString(106, StringUtil.checkNull(sendList.get("spClothesMater").toString()).trim());
				pstmt.setString(107, StringUtil.checkNull(sendList.get("spIsShield").toString()).trim());
				pstmt.setString(108, StringUtil.checkNull(sendList.get("spESIRApproval").toString()).trim());
				pstmt.setString(109, StringUtil.checkNull(sendList.get("spISIRApproval").toString()).trim());
				pstmt.setString(110, StringUtil.checkNull(sendList.get("spConAppNoESIR").toString()).trim());
				pstmt.setString(111, StringUtil.checkNull(sendList.get("spLayer").toString()).trim());
				pstmt.setString(112, StringUtil.checkNull(sendList.get("spOrgDskPartNo").toString()).trim());
				pstmt.setString(113, StringUtil.checkNull(sendList.get("spPCBMaterial").toString()).trim());
				pstmt.setString(114, StringUtil.checkNull(sendList.get("spTg").toString()).trim());
				pstmt.setString(115, StringUtil.checkNull(sendList.get("spCharact").toString()).trim());
				pstmt.setString(116, StringUtil.checkNull(sendList.get("spSurfaceTreat").toString()).trim());
				pstmt.setString(117, StringUtil.checkNull(sendList.get("spAppearanProc").toString()).trim());
				pstmt.setString(118, StringUtil.checkNull(sendList.get("spSoldResColor").toString()).trim());
				pstmt.setString(119, StringUtil.checkNull(sendList.get("spInstallPos").toString()).trim());
				pstmt.setString(120, StringUtil.checkNull(sendList.get("spSwVersion").toString()).trim());
				pstmt.setString(121, StringUtil.checkNull(sendList.get("spUnitUnit").toString()).trim());
				pstmt.setString(122, StringUtil.checkNull(sendList.get("spResUnit").toString()).trim());
				pstmt.setString(123, StringUtil.checkNull(sendList.get("spINDUnit").toString()).trim());
				pstmt.setString(124, StringUtil.checkNull(sendList.get("spCapUnit").toString()).trim());
				pstmt.setString(125, StringUtil.checkNull(sendList.get("spRLCPackType").toString()).trim());
				pstmt.setString(126, StringUtil.checkNull(sendList.get("spRLCTolerance").toString()).trim());
				pstmt.setString(127, StringUtil.checkNull(sendList.get("spFestPrevent").toString()).trim());
				pstmt.setString(128, StringUtil.checkNull(sendList.get("spConnCombDir").toString()).trim());
				pstmt.setString(129, StringUtil.checkNull(sendList.get("spCertified").toString()).trim());
				pstmt.setString(130, StringUtil.checkNull(sendList.get("spPackageSpec").toString()).trim());
				pstmt.setString(131, StringUtil.checkNull(sendList.get("spTabSize").toString()).trim());
				pstmt.setString(132, StringUtil.checkNull(sendList.get("spSealType").toString()).trim());
				pstmt.setString(133, StringUtil.checkNull(sendList.get("spStudSize").toString()).trim());
				pstmt.setString(134, StringUtil.checkNull(sendList.get("spPitch").toString()).trim());
				pstmt.setString(135, StringUtil.checkNull(sendList.get("spSoldering").toString()).trim());
				pstmt.setString(136, StringUtil.checkNull(sendList.get("spConstrucMeth").toString()).trim());
				pstmt.setString(137, StringUtil.checkNull(sendList.get("spOptimumTemp").toString()).trim());
				pstmt.setString(138, StringUtil.checkNull(sendList.get("spContactRes").toString()).trim());
				pstmt.setString(139, StringUtil.checkNull(sendList.get("spInsulatRes").toString()).trim());
				pstmt.setString(140, StringUtil.checkNull(sendList.get("spConntHeight").toString()).trim());
				pstmt.setString(141, StringUtil.checkNull(sendList.get("spCableConMeth").toString()).trim());
				pstmt.setString(142, StringUtil.checkNull(sendList.get("spTerminalType").toString()).trim());
				pstmt.setString(143, StringUtil.checkNull(sendList.get("spTermBarrelSz").toString()).trim());
				pstmt.setString(144, StringUtil.checkNull(sendList.get("spTermPrezType").toString()).trim());
				pstmt.setString(145, StringUtil.checkNull(sendList.get("spGWITMaterAt").toString()).trim());
				pstmt.setString(146, StringUtil.checkNull(sendList.get("spInterface").toString()).trim());
				pstmt.setString(147, StringUtil.checkNull(sendList.get("spPinNShape").toString()).trim());
				pstmt.setString(148, StringUtil.checkNull(sendList.get("spSUBSuppliy").toString()).trim());
				pstmt.setString(149, StringUtil.checkNull(sendList.get("spCodingNColor").toString()).trim());
				pstmt.setString(150, StringUtil.checkNull(sendList.get("spPlant").toString()).trim());
				pstmt.setString(151, StringUtil.checkNull(sendList.get("spPuchaseGroup").toString()).trim());
				pstmt.setString(152, StringUtil.checkNull(sendList.get("spDevManNm").toString()).trim());
				pstmt.setString(153, StringUtil.checkNull(sendList.get("spDesignManNm").toString()).trim());
				pstmt.setString(154, StringUtil.checkNull(sendList.get("spManufacManNm").toString()).trim());
				pstmt.setString(155, StringUtil.checkNull(sendList.get("spMContractSAt").toString()).trim());
				pstmt.setString(156, StringUtil.checkNull(sendList.get("spMMoldAt").toString()).trim());
				pstmt.setString(157, StringUtil.checkNull(sendList.get("spMMakingAt").toString()).trim());
				pstmt.setString(158, StringUtil.checkNull(sendList.get("spMProdAt").toString()).trim());
				pstmt.setString(159, StringUtil.checkNull(sendList.get("spDieWhere").toString()).trim());
				pstmt.setString(160, StringUtil.checkNull(sendList.get("spObjectiveCT").toString()).trim());
				pstmt.setString(161, StringUtil.checkNull(sendList.get("spCavityStd").toString()).trim());
				pstmt.setString(162, StringUtil.checkNull(sendList.get("spMountWayApE").toString()).trim());
				pstmt.setString(163, StringUtil.checkNull(sendList.get("spThickWH").toString()).trim());
				pstmt.setString(164, StringUtil.checkNull(sendList.get("spPropEtc").toString()).trim());
				pstmt.setString(165, StringUtil.checkNull(sendList.get("spHighVoltageSensingLimit").toString()).trim());
				pstmt.setString(166, StringUtil.checkNull(sendList.get("spMovVoltage").toString()).trim());
				pstmt.setString(167, StringUtil.checkNull(sendList.get("spToleranceSensing").toString()).trim());
				pstmt.setString(168, StringUtil.checkNull(sendList.get("spEsirApprove").toString()).trim());
				pstmt.setString(169, StringUtil.checkNull(sendList.get("spMainChipset").toString()).trim());
				pstmt.setString(170, StringUtil.checkNull(sendList.get("spFrequency").toString()).trim());
				pstmt.setString(171, StringUtil.checkNull(sendList.get("spDcpower").toString()).trim());
				pstmt.setString(172, StringUtil.checkNull(sendList.get("spInterfaceIt").toString()).trim());
				pstmt.setString(173, StringUtil.checkNull(sendList.get("spFeatures").toString()).trim());
				pstmt.setString(174, StringUtil.checkNull(sendList.get("spDevSpec").toString()).trim());
				pstmt.setString(175, StringUtil.checkNull(sendList.get("spFlameLevel").toString()).trim());
				pstmt.setString(176, StringUtil.checkNull(sendList.get("spERatedVoltage").toString()).trim());
				pstmt.setString(177, StringUtil.checkNull(sendList.get("spQCNo").toString()).trim());
				pstmt.setString(178, StringUtil.checkNull(sendList.get("spActuatorLctn").toString()).trim());
				pstmt.setString(179, StringUtil.checkNull(sendList.get("spMaxFrequency").toString()).trim());
				pstmt.setString(180, StringUtil.checkNull(sendList.get("spImpedance").toString()).trim());
				pstmt.setString(181, StringUtil.checkNull(sendList.get("spAssemblyMaterial").toString()).trim());
				pstmt.setString(182, StringUtil.checkNull(sendList.get("spDescription").toString()).trim());
				pstmt.setString(183, StringUtil.checkNull(sendList.get("spImgFile").toString()).trim());
				pstmt.setString(184, StringUtil.checkNull(sendList.get("sp2DpdfFile").toString()).trim());
				pstmt.setString(185, StringUtil.checkNull(sendList.get("sp3DpdfFile").toString()).trim());
				pstmt.setString(186, StringUtil.checkNull(sendList.get("spStepFile").toString()).trim());
				pstmt.setString(187, StringUtil.checkNull(sendList.get("spIgsFile").toString()).trim());
				pstmt.setString(188, StringUtil.checkNull(sendList.get("spInstructionsFile").toString()).trim());
				pstmt.setString(189, "N");
				pstmt.setString(190, StringUtil.checkNull(sendList.get("spMasterName").toString()).trim());
				pstmt.setString(191, StringUtil.checkNull(sendList.get("spMasterEmail").toString()).trim());

				pstmt.setString(192, StringUtil.checkNull(sendList.get("spCategoryCode").toString()).trim());
				pstmt.setString(193, StringUtil.checkNull(sendList.get("spClassification").toString()).trim());
				pstmt.setString(194, StringUtil.checkNull(sendList.get("PartName").toString()).trim());
				pstmt.setString(195, StringUtil.checkNull(sendList.get("HpPartNumber").toString()).trim());
				pstmt.setString(196, StringUtil.checkNull(sendList.get("spDivision").toString()).trim());
				pstmt.setString(197, StringUtil.checkNull(sendList.get("spProjectNo").toString()).trim());
				pstmt.setString(198, StringUtil.checkNull(sendList.get("spEoNo").toString()).trim());
				pstmt.setString(199, StringUtil.checkNull(sendList.get("spPartStyle").toString()).trim());
				pstmt.setString(200, StringUtil.checkNull(sendList.get("spPartNameHis").toString()).trim());
				pstmt.setString(201, StringUtil.checkNull(sendList.get("spPartRevision").toString()).trim());
				pstmt.setString(202, StringUtil.checkNull(sendList.get("spPartType").toString()).trim());
				pstmt.setString(203, StringUtil.checkNull(sendList.get("spPartDevLevel").toString()).trim());
				pstmt.setString(204, StringUtil.checkNull(sendList.get("spIsDeleted").toString()).trim());
				pstmt.setString(205, StringUtil.checkNull(sendList.get("spBOMFlag").toString()).trim());
				pstmt.setString(206, StringUtil.checkNull(sendList.get("spWeightUnit").toString()).trim());
				pstmt.setString(207, StringUtil.checkNull(sendList.get("spNetWeight").toString()).trim());
				pstmt.setString(208, StringUtil.checkNull(sendList.get("spTotalWeight").toString()).trim());
				pstmt.setString(209, StringUtil.checkNull(sendList.get("spScrabWeight").toString()).trim());
				pstmt.setString(210, StringUtil.checkNull(sendList.get("spIsYazaki").toString()).trim());
				pstmt.setString(211, StringUtil.checkNull(sendList.get("spYazakiNo").toString()).trim());
				pstmt.setString(212, StringUtil.checkNull(sendList.get("spManufAt").toString()).trim());
				pstmt.setString(213, StringUtil.checkNull(sendList.get("spManufacPlace").toString()).trim());
				pstmt.setString(214, StringUtil.checkNull(sendList.get("spCustomRev").toString()).trim());
				pstmt.setString(215, StringUtil.checkNull(sendList.get("spScrabCode").toString()).trim());
				pstmt.setString(216, StringUtil.checkNull(sendList.get("spWaterProof").toString()).trim());
				pstmt.setString(217, StringUtil.checkNull(sendList.get("spMaterialMark").toString()).trim());
				pstmt.setString(218, StringUtil.checkNull(sendList.get("spColor").toString()).trim());
				pstmt.setString(219, StringUtil.checkNull(sendList.get("spColorPurch").toString()).trim());
				pstmt.setString(220, StringUtil.checkNull(sendList.get("spColorElec").toString()).trim());
				pstmt.setString(221, StringUtil.checkNull(sendList.get("spSeries").toString()).trim());
				pstmt.setString(222, StringUtil.checkNull(sendList.get("spSeriesLAMP").toString()).trim());
				pstmt.setString(223, StringUtil.checkNull(sendList.get("spSeriesBulb").toString()).trim());
				pstmt.setString(224, StringUtil.checkNull(sendList.get("spProdSize").toString()).trim());
				pstmt.setString(225, StringUtil.checkNull(sendList.get("spEnvFriend").toString()).trim());
				pstmt.setString(226, StringUtil.checkNull(sendList.get("spTGenConn").toString()).trim());
				pstmt.setString(227, StringUtil.checkNull(sendList.get("spTPCBConn").toString()).trim());
				pstmt.setString(228, StringUtil.checkNull(sendList.get("spTLAMPConn").toString()).trim());
				pstmt.setString(229, StringUtil.checkNull(sendList.get("spTBulbConn").toString()).trim());
				pstmt.setString(230, StringUtil.checkNull(sendList.get("spTHiVolt").toString()).trim());
				pstmt.setString(231, StringUtil.checkNull(sendList.get("spTCharger").toString()).trim());
				pstmt.setString(232, StringUtil.checkNull(sendList.get("spT2Charger").toString()).trim());
				pstmt.setString(233, StringUtil.checkNull(sendList.get("spT1HiVoltFuz").toString()).trim());
				pstmt.setString(234, StringUtil.checkNull(sendList.get("spTHiVoltFuse").toString()).trim());
				pstmt.setString(235, StringUtil.checkNull(sendList.get("spTJnB").toString()).trim());
				pstmt.setString(236, StringUtil.checkNull(sendList.get("spTPRA").toString()).trim());
				pstmt.setString(237, StringUtil.checkNull(sendList.get("spTGNSS").toString()).trim());
				pstmt.setString(238, StringUtil.checkNull(sendList.get("spTComModule").toString()).trim());
				pstmt.setString(239, StringUtil.checkNull(sendList.get("spTMultiMedUnit").toString()).trim());
				pstmt.setString(240, StringUtil.checkNull(sendList.get("spLanceType").toString()).trim());
				pstmt.setString(241, StringUtil.checkNull(sendList.get("spNoOfPole").toString()).trim());
				pstmt.setString(242, StringUtil.checkNull(sendList.get("spMTerminal").toString()).trim());
				pstmt.setString(243, StringUtil.checkNull(sendList.get("spMConnector").toString()).trim());
				pstmt.setString(244, StringUtil.checkNull(sendList.get("spMatchBulb").toString()).trim());
				pstmt.setString(245, StringUtil.checkNull(sendList.get("spMClip").toString()).trim());
				pstmt.setString(246, StringUtil.checkNull(sendList.get("spMRH").toString()).trim());
				pstmt.setString(247, StringUtil.checkNull(sendList.get("spMCover").toString()).trim());
				pstmt.setString(248, StringUtil.checkNull(sendList.get("spLockingType").toString()).trim());
				pstmt.setString(249, StringUtil.checkNull(sendList.get("spLockTTML").toString()).trim());
				pstmt.setString(250, StringUtil.checkNull(sendList.get("spLockTConn").toString()).trim());
				pstmt.setString(251, StringUtil.checkNull(sendList.get("spMWireSeal").toString()).trim());
				pstmt.setString(252, StringUtil.checkNull(sendList.get("spRepresentM").toString()).trim());
				pstmt.setString(253, StringUtil.checkNull(sendList.get("spMaterMaker").toString()).trim());
				pstmt.setString(254, StringUtil.checkNull(sendList.get("spMaterType").toString()).trim());
				pstmt.setString(255, StringUtil.checkNull(sendList.get("spMaterialInfo").toString()).trim());
				pstmt.setString(256, StringUtil.checkNull(sendList.get("spMaterNotFe").toString()).trim());
				pstmt.setString(257, StringUtil.checkNull(sendList.get("spMaterDie").toString()).trim());
				pstmt.setString(258, StringUtil.checkNull(sendList.get("spMaterPurch").toString()).trim());
				pstmt.setString(259, StringUtil.checkNull(sendList.get("spPlating").toString()).trim());
				pstmt.setString(260, StringUtil.checkNull(sendList.get("spPlatingPurch").toString()).trim());
				pstmt.setString(261, StringUtil.checkNull(sendList.get("spCustomPartNo").toString()).trim());
				pstmt.setString(262, StringUtil.checkNull(sendList.get("spPermitVolt").toString()).trim());
				pstmt.setString(263, StringUtil.checkNull(sendList.get("spWireRangeAWG").toString()).trim());
				pstmt.setString(264, StringUtil.checkNull(sendList.get("spWireRAWGElec").toString()).trim());
				pstmt.setString(265, StringUtil.checkNull(sendList.get("spWireRangeMm").toString()).trim());
				pstmt.setString(266, StringUtil.checkNull(sendList.get("spTabThickness").toString()).trim());
				pstmt.setString(267, StringUtil.checkNull(sendList.get("spMaterThick").toString()).trim());
				pstmt.setString(268, StringUtil.checkNull(sendList.get("spBracketSizeD").toString()).trim());
				pstmt.setString(269, StringUtil.checkNull(sendList.get("spBracketSizeH").toString()).trim());
				pstmt.setString(270, StringUtil.checkNull(sendList.get("spBracketSizeT").toString()).trim());
				pstmt.setString(271, StringUtil.checkNull(sendList.get("spRelayCapa").toString()).trim());
				pstmt.setString(272, StringUtil.checkNull(sendList.get("spEResistVal").toString()).trim());
				pstmt.setString(273, StringUtil.checkNull(sendList.get("spVoltSensCapa").toString()).trim());
				pstmt.setString(274, StringUtil.checkNull(sendList.get("spManufPartNo").toString()).trim());
				pstmt.setString(275, StringUtil.checkNull(sendList.get("spValueValue").toString()).trim());
				pstmt.setString(276, StringUtil.checkNull(sendList.get("spTolerance").toString()).trim());
				pstmt.setString(277, StringUtil.checkNull(sendList.get("spManufacturer").toString()).trim());
				pstmt.setString(278, StringUtil.checkNull(sendList.get("spRatedVoltage").toString()).trim());
				pstmt.setString(279, StringUtil.checkNull(sendList.get("spWatt").toString()).trim());
				pstmt.setString(280, StringUtil.checkNull(sendList.get("spOperTemp").toString()).trim());
				pstmt.setString(281, StringUtil.checkNull(sendList.get("spStoreTemp").toString()).trim());
				pstmt.setString(282, StringUtil.checkNull(sendList.get("spPackageType").toString()).trim());
				pstmt.setString(283, StringUtil.checkNull(sendList.get("spMSL").toString()).trim());
				pstmt.setString(284, StringUtil.checkNull(sendList.get("spESD").toString()).trim());
				pstmt.setString(285, StringUtil.checkNull(sendList.get("spAECQ").toString()).trim());
				pstmt.setString(286, StringUtil.checkNull(sendList.get("spCharact1").toString()).trim());
				pstmt.setString(287, StringUtil.checkNull(sendList.get("spCharact2").toString()).trim());
				pstmt.setString(288, StringUtil.checkNull(sendList.get("spHoleSize").toString()).trim());
				pstmt.setString(289, StringUtil.checkNull(sendList.get("spWireRangeSQ").toString()).trim());
				pstmt.setString(290, StringUtil.checkNull(sendList.get("spWATTW").toString()).trim());
				pstmt.setString(291, StringUtil.checkNull(sendList.get("spSizemm").toString()).trim());
				pstmt.setString(292, StringUtil.checkNull(sendList.get("spPermitTempC").toString()).trim());
				pstmt.setString(293, StringUtil.checkNull(sendList.get("spIsResin").toString()).trim());
				pstmt.setString(294, StringUtil.checkNull(sendList.get("spThickness").toString()).trim());
				pstmt.setString(295, StringUtil.checkNull(sendList.get("spHoleShape").toString()).trim());
				pstmt.setString(296, StringUtil.checkNull(sendList.get("spCapaEResist").toString()).trim());
				pstmt.setString(297, StringUtil.checkNull(sendList.get("spClothesMater").toString()).trim());
				pstmt.setString(298, StringUtil.checkNull(sendList.get("spIsShield").toString()).trim());
				pstmt.setString(299, StringUtil.checkNull(sendList.get("spESIRApproval").toString()).trim());
				pstmt.setString(300, StringUtil.checkNull(sendList.get("spISIRApproval").toString()).trim());
				pstmt.setString(301, StringUtil.checkNull(sendList.get("spConAppNoESIR").toString()).trim());
				pstmt.setString(302, StringUtil.checkNull(sendList.get("spLayer").toString()).trim());
				pstmt.setString(303, StringUtil.checkNull(sendList.get("spOrgDskPartNo").toString()).trim());
				pstmt.setString(304, StringUtil.checkNull(sendList.get("spPCBMaterial").toString()).trim());
				pstmt.setString(305, StringUtil.checkNull(sendList.get("spTg").toString()).trim());
				pstmt.setString(306, StringUtil.checkNull(sendList.get("spCharact").toString()).trim());
				pstmt.setString(307, StringUtil.checkNull(sendList.get("spSurfaceTreat").toString()).trim());
				pstmt.setString(308, StringUtil.checkNull(sendList.get("spAppearanProc").toString()).trim());
				pstmt.setString(309, StringUtil.checkNull(sendList.get("spSoldResColor").toString()).trim());
				pstmt.setString(310, StringUtil.checkNull(sendList.get("spInstallPos").toString()).trim());
				pstmt.setString(311, StringUtil.checkNull(sendList.get("spSwVersion").toString()).trim());
				pstmt.setString(312, StringUtil.checkNull(sendList.get("spUnitUnit").toString()).trim());
				pstmt.setString(313, StringUtil.checkNull(sendList.get("spResUnit").toString()).trim());
				pstmt.setString(314, StringUtil.checkNull(sendList.get("spINDUnit").toString()).trim());
				pstmt.setString(315, StringUtil.checkNull(sendList.get("spCapUnit").toString()).trim());
				pstmt.setString(316, StringUtil.checkNull(sendList.get("spRLCPackType").toString()).trim());
				pstmt.setString(317, StringUtil.checkNull(sendList.get("spRLCTolerance").toString()).trim());
				pstmt.setString(318, StringUtil.checkNull(sendList.get("spFestPrevent").toString()).trim());
				pstmt.setString(319, StringUtil.checkNull(sendList.get("spConnCombDir").toString()).trim());
				pstmt.setString(320, StringUtil.checkNull(sendList.get("spCertified").toString()).trim());
				pstmt.setString(321, StringUtil.checkNull(sendList.get("spPackageSpec").toString()).trim());
				pstmt.setString(322, StringUtil.checkNull(sendList.get("spTabSize").toString()).trim());
				pstmt.setString(323, StringUtil.checkNull(sendList.get("spSealType").toString()).trim());
				pstmt.setString(324, StringUtil.checkNull(sendList.get("spStudSize").toString()).trim());
				pstmt.setString(325, StringUtil.checkNull(sendList.get("spPitch").toString()).trim());
				pstmt.setString(326, StringUtil.checkNull(sendList.get("spSoldering").toString()).trim());
				pstmt.setString(327, StringUtil.checkNull(sendList.get("spConstrucMeth").toString()).trim());
				pstmt.setString(328, StringUtil.checkNull(sendList.get("spOptimumTemp").toString()).trim());
				pstmt.setString(329, StringUtil.checkNull(sendList.get("spContactRes").toString()).trim());
				pstmt.setString(330, StringUtil.checkNull(sendList.get("spInsulatRes").toString()).trim());
				pstmt.setString(331, StringUtil.checkNull(sendList.get("spConntHeight").toString()).trim());
				pstmt.setString(332, StringUtil.checkNull(sendList.get("spCableConMeth").toString()).trim());
				pstmt.setString(333, StringUtil.checkNull(sendList.get("spTerminalType").toString()).trim());
				pstmt.setString(334, StringUtil.checkNull(sendList.get("spTermBarrelSz").toString()).trim());
				pstmt.setString(335, StringUtil.checkNull(sendList.get("spTermPrezType").toString()).trim());
				pstmt.setString(336, StringUtil.checkNull(sendList.get("spGWITMaterAt").toString()).trim());
				pstmt.setString(337, StringUtil.checkNull(sendList.get("spInterface").toString()).trim());
				pstmt.setString(338, StringUtil.checkNull(sendList.get("spPinNShape").toString()).trim());
				pstmt.setString(339, StringUtil.checkNull(sendList.get("spSUBSuppliy").toString()).trim());
				pstmt.setString(340, StringUtil.checkNull(sendList.get("spCodingNColor").toString()).trim());
				pstmt.setString(341, StringUtil.checkNull(sendList.get("spPlant").toString()).trim());
				pstmt.setString(342, StringUtil.checkNull(sendList.get("spPuchaseGroup").toString()).trim());
				pstmt.setString(343, StringUtil.checkNull(sendList.get("spDevManNm").toString()).trim());
				pstmt.setString(344, StringUtil.checkNull(sendList.get("spDesignManNm").toString()).trim());
				pstmt.setString(345, StringUtil.checkNull(sendList.get("spManufacManNm").toString()).trim());
				pstmt.setString(346, StringUtil.checkNull(sendList.get("spMContractSAt").toString()).trim());
				pstmt.setString(347, StringUtil.checkNull(sendList.get("spMMoldAt").toString()).trim());
				pstmt.setString(348, StringUtil.checkNull(sendList.get("spMMakingAt").toString()).trim());
				pstmt.setString(349, StringUtil.checkNull(sendList.get("spMProdAt").toString()).trim());
				pstmt.setString(350, StringUtil.checkNull(sendList.get("spDieWhere").toString()).trim());
				pstmt.setString(351, StringUtil.checkNull(sendList.get("spObjectiveCT").toString()).trim());
				pstmt.setString(352, StringUtil.checkNull(sendList.get("spCavityStd").toString()).trim());
				pstmt.setString(353, StringUtil.checkNull(sendList.get("spMountWayApE").toString()).trim());
				pstmt.setString(354, StringUtil.checkNull(sendList.get("spThickWH").toString()).trim());
				pstmt.setString(355, StringUtil.checkNull(sendList.get("spPropEtc").toString()).trim());
				pstmt.setString(356, StringUtil.checkNull(sendList.get("spHighVoltageSensingLimit").toString()).trim());
				pstmt.setString(357, StringUtil.checkNull(sendList.get("spMovVoltage").toString()).trim());
				pstmt.setString(358, StringUtil.checkNull(sendList.get("spToleranceSensing").toString()).trim());
				pstmt.setString(359, StringUtil.checkNull(sendList.get("spEsirApprove").toString()).trim());
				pstmt.setString(360, StringUtil.checkNull(sendList.get("spMainChipset").toString()).trim());
				pstmt.setString(361, StringUtil.checkNull(sendList.get("spFrequency").toString()).trim());
				pstmt.setString(362, StringUtil.checkNull(sendList.get("spDcpower").toString()).trim());
				pstmt.setString(363, StringUtil.checkNull(sendList.get("spInterfaceIt").toString()).trim());
				pstmt.setString(364, StringUtil.checkNull(sendList.get("spFeatures").toString()).trim());
				pstmt.setString(365, StringUtil.checkNull(sendList.get("spDevSpec").toString()).trim());
				pstmt.setString(366, StringUtil.checkNull(sendList.get("spFlameLevel").toString()).trim());
				pstmt.setString(367, StringUtil.checkNull(sendList.get("spERatedVoltage").toString()).trim());
				pstmt.setString(368, StringUtil.checkNull(sendList.get("spQCNo").toString()).trim());
				pstmt.setString(369, StringUtil.checkNull(sendList.get("spActuatorLctn").toString()).trim());
				pstmt.setString(370, StringUtil.checkNull(sendList.get("spMaxFrequency").toString()).trim());
				pstmt.setString(371, StringUtil.checkNull(sendList.get("spImpedance").toString()).trim());
				pstmt.setString(372, StringUtil.checkNull(sendList.get("spAssemblyMaterial").toString()).trim());
				pstmt.setString(373, StringUtil.checkNull(sendList.get("spDescription").toString()).trim());
				pstmt.setString(374, StringUtil.checkNull(sendList.get("spImgFile").toString()).trim());
				pstmt.setString(375, StringUtil.checkNull(sendList.get("sp2DpdfFile").toString()).trim());
				pstmt.setString(376, StringUtil.checkNull(sendList.get("sp3DpdfFile").toString()).trim());
				pstmt.setString(377, StringUtil.checkNull(sendList.get("spStepFile").toString()).trim());
				pstmt.setString(378, StringUtil.checkNull(sendList.get("spIgsFile").toString()).trim());
				pstmt.setString(379, StringUtil.checkNull(sendList.get("spInstructionsFile").toString()).trim());
				pstmt.setString(380, "N");
				pstmt.setString(381, StringUtil.checkNull(sendList.get("spMasterName").toString()).trim());
				pstmt.setString(382, StringUtil.checkNull(sendList.get("spMasterEmail").toString()).trim());

				complet = pstmt.executeUpdate();

				sb.delete(0, sb.length());
			}

		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (pstmt != null) {
				pstmt.close();
			}

		}
		return complet;
	}

	public void deletePartAttrIf() throws Exception {

		PreparedStatement pstmt = null;
		try {
			StringBuilder sb = new StringBuilder();
			sb.append(" DELETE FROM KETPLM.dbo.WKET_IF002 ");

			pstmt = conn.prepareStatement(sb.toString());
			pstmt.executeUpdate();

		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (pstmt != null) {
				pstmt.close();
			}

		}

	}

	/**
	 * 함수명 : SearchRepass 설명 : 개발담당자 결재
	 * 
	 * @param
	 * @return ArrayList
	 * @throws Exception
	 * @throws 작성자
	 *             : 황정태 작성일자 : 2012. 07. 02.
	 */
	public int savePartAttrIf(List<Map<String, Object>> partAttrList) throws Exception {
		PreparedStatement pstmt = null;
		int complet = 0;
		try {
			StringBuilder sb = new StringBuilder();

			for (Map<String, Object> sendList : partAttrList) {

				sb.append(" INSERT INTO KETPLM.dbo.WKET_IF002 ");
				sb.append("\n (	classCode,ClassAttr,ClassAttrEname, ClassCount, HomepageYN");
				sb.append("\n )");
				sb.append("\n VALUES");
				sb.append("\n ( ?, ? , ?, ?, ?)");

				pstmt = conn.prepareStatement(sb.toString());
				pstmt.setString(1, sendList.get("CLASSCODE").toString().trim());
				pstmt.setString(2, sendList.get("ATTRCODE").toString().trim());
				pstmt.setString(3, sendList.get("ATTRENAME").toString().trim());
				pstmt.setString(4, sendList.get("INDEXSORT").toString().trim());
				pstmt.setString(5, sendList.get("HPYN").toString().trim());

				complet = pstmt.executeUpdate();

				sb.delete(0, sb.length());
			}

		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (pstmt != null) {
				pstmt.close();
			}

		}
		return complet;
	}
}