DROP SEQUENCE SEQ_ECR_NUM;
DROP SEQUENCE SEQ_ECO_NUM;
DROP SEQUENCE SEQ_PLAN_NUM;

CREATE SEQUENCE SEQ_ECR_NUM
INCREMENT BY 1
START WITH 001
MAXVALUE 999
NOCYCLE;

CREATE SEQUENCE SEQ_ECO_NUM
INCREMENT BY 1
START WITH 001
MAXVALUE 999
NOCYCLE;

CREATE SEQUENCE SEQ_PLAN_NUM
INCREMENT BY 1
START WITH 001
MAXVALUE 999
NOCYCLE;
